{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "axelar-node.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - rpc.axelar.{{ .Values.ingress.domain }}
    secretName: rpc.axelar-{{ .Values.ingress.domain }}-tls
  - hosts:
    - api.axelar.{{ .Values.ingress.domain }}
    secretName: api.axelar-{{ .Values.ingress.domain }}-tls
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: rpc.axelar.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: axelar-fullnode
                port:
                  number: 26657
    - host: api.axelar.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: axelar-fullnode
                port:
                  number: 1317
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "axelar-node.fullname" . }}-grpc-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - grpc.axelar.{{ .Values.ingress.domain }}
    secretName: grpc.axelar-{{ .Values.ingress.domain }}-tls
  {{ end }}
spec:
  ingressClassName: nginx
  rules:
    - host: grpc.axelar.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: axelar-fullnode
                port:
                  number: 9090
{{- end }}