{{- if .Values.fullnode.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: shentu-fullnode
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 1317
      name: shentu-api
    - port: 9090
      name: shentu-grpc
    - port: 26660
      name: metrics
    - port: 26657
      name: shentu-rpc
  selector:
    shentu.network/fullnode: "{{ .Values.shentu_node.moniker }}"
{{- else }}
---
apiVersion: v1
kind: Service
metadata:
  name: shentu-validator
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 26656
      name: shentu-p2p
    {{- if .Values.validator.tmkms }}
    - port: 26659
      name: shentu-kms
    {{- end }}
  selector:
    app: "shentu-validator"
{{- end }}
