{{ if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: {{ .Values.monitoring.promReleaseName }}
  name: {{ .Values.monitoring.name }}-{{ .Release.Name }}
  namespace: {{ .Values.monitoring.namespace }}
spec:
  endpoints:
  - interval: 60s
    port: metrics
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cosmos-validator-watcher
{{- end }}
