{{- if .Values.fullnode.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: bitsong-fullnode
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 1317
      name: api
    - port: 9090
      name: grpc
    - port: 26656
      name: p2p
    - port: 26657
      name: rpc
  selector:
    bitsong.network/fullnode: "{{ .Values.bitsong_node.moniker }}"
{{- else }}
---
apiVersion: v1
kind: Service
metadata:
  name: bitsong-validator
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 26656
      name: p2p
    - port: 26660
      name: metrics
    {{- if .Values.validator.tmkms }}
    - port: 26659
      name: kms
    {{- end }}
  selector:
    app: "bitsong-validator"
{{- end }}
