{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "evmos-node.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations: {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - rpc.evmos.{{ .Values.ingress.domain }}
      secretName: rpc.evmos-{{ .Values.ingress.domain }}-tls
    - hosts:
        - api.evmos.{{ .Values.ingress.domain }}
      secretName: api.evmos-{{ .Values.ingress.domain }}-tls
  {{- end }}
  rules:
    - host: rpc.evmos.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: evmos-fullnode
                port:
                  number: 26657
    - host: api.evmos.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: evmos-fullnode
                port:
                  number: 1317
{{- end }}
---
{{- if .Values.ingress.grpc.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "evmos-node.fullname" . }}-grpc-ingress
  namespace: {{ .Release.Namespace }}
  annotations: {{- toYaml .Values.ingress.grpc.annotations | nindent 4 }}
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.grpc.tls }}
  tls:
    - hosts:
        - grpc.evmos.{{ .Values.ingress.domain }}
      secretName: grpc.evmos-{{ .Values.ingress.domain }}-tls
  {{- end }}
  rules:
    - host: grpc.evmos.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: evmos-fullnode
                port:
                  number: 9090
{{- end }}
