# Default values for akash-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "ghcr.io/akash-network/cosmos-omnibus"
  tag: "v0.4.3-rc1-akash-v0.30.0"
  pullPolicy: IfNotPresent

# Common Values

keyring_backend: "test"
home: "/root/.akash"
debug: "false"

# Set Values to run a single akash (Certik) node connected to an existing network
# Defaults to mainnet
akash_node:
  # snapshot_provider can be either "polkachu" (2Gi), "autostake" (1Gi). Otherwise it'll default to a much larger in size.
  snapshot_provider: "polkachu"
  api_enable: "false"
  moniker: yourminikerhere
  chainid: akashnet-2
  # disable PEX when nodes have issues with syncing / catching up / peer dial errors/flood
  minimum_gas_prices: 0.025uakt
  net: https://snapshots.polkachu.com/genesis/akash/genesis.json
  peers: 3dd862780dde4b86688c086fcf27a2ac08d29e3a@188.214.129.233:29656,ebc272824924ea1a27ea3183dd0b9ba713494f83@195.3.223.168:26696,ebeea522e069f9037876e13f73310a601cfcff8a@95.179.212.224:26656,2b760f136e6e4f420cc38e5f1674307935c4149b@31.7.196.97:12856,731394cfc97fca39d52334eb703413ada5273098@51.81.107.4:26656,8e81452f92a87acd45c071d6e7f87d967ab9db9e@95.111.246.150:26656,4799e2f3af4eebff187dc0ee9b5057c86bed6173@95.217.202.49:39656,b77dac854047574b0f15ac70db3698b5a1bbd48c@66.172.36.136:16656,69132a605f80a9a1ee9532f7eb925ae5fa613e23@107.191.44.212:26656,43544bc781b88d6785420427926d86a5332940b3@142.132.131.184:26676,86f866a645bcc25d3d26fe8dffbd603ebfc0d6ee@142.132.158.93:12856,77ef372cef4f03a74eb4a0d5454738650adfd9b3@46.38.233.40:26656,1f7b4e891247fbae1375e7062fc22b0ca0a4e51d@159.89.106.172:26656,43400f4ec45734bafdb8f7c5de9678e75f9c0f08@62.131.218.3:26656,7001280de176c2ce4d9c06c05179a6ebe25a46fc@13.228.88.45:26656,aff5e4ac6c17965ea798b6d303b06ff19196835a@83.136.255.212:26656,5a37cdeebcdf30bda5aafed7a4f6badb4b5bddb2@51.158.233.73:26656,6e82ac725aa4d8df49c1e9277606e1d75199537a@51.91.70.90:39656,4478e0600c6726bbfbe3babee7079e7c4ae0e59d@84.17.42.200:29656,9aa4c9097c818871e45aaca4118a9fe5e86c60e2@135.181.113.227:1506,cefbfea7efe893b060f6b755bde13072ba8201e6@31.7.196.25:26656,02b5a74f0cc909045efe170da3cc5706de2c0be5@88.208.243.62:26656,ba4ea7c936a3321bb4c65c057f7d5792b5011a25@103.180.28.208:26656,00a39ac3ec012ffa3116a162c17f49df484d0298@34.34.136.79:26656,bd2525f1a86af8b1a3798c04387f47f0c0627d24@159.223.201.38:26656,1e8aaf3654887a05caeb0c1f73ce39e859e2f0c9@159.223.201.86:26656,dda1f59957f767e20b0fc64b1c915b4799fc0cc5@159.223.201.93:26656,d087066f61fa3e286f3a6dc96c08c2564a4757e8@5.10.24.74:26656,f9215993d48d8e0abc31cea931d573a45d201ac8@65.108.232.104:12856,c21a8baf1c0c27c23ff74d6b97b29d4a7ee3ad5a@31.210.34.170:26656,e5a3deca200af80c7f90e9627a20d29f60936f0b@85.10.197.58:12856,fd0ec00f76f58680c0c2f3ebd285217fdca48452@68.233.228.216:26656,4bac1c3cfc22e56f8d7be4ee4b55faef4dc03758@37.59.18.110:26656,fb36358d0de87bd427d084a49dc0a9c894971429@35.232.84.6:26656,37201c92625df2814a55129f73f10ab6aa2edc35@95.214.53.215:26696,05c30fd95b888ca8df8171ce65a06f1de683d6e3@84.252.129.17:26656,88c01b3b03be014b8733e33fbf02af2b716ce753@109.123.246.15:26656,acae777f5f6ab9e45aef6757dcee9343ea09e4d7@65.108.128.240:26656,b0445c6d52e9d7388c85ca50e14e0ebfa2ae8363@68.186.247.133:26656,6adc00bef235246c90757547d5f0703d6a548460@178.128.82.28:26656,dfb5e651ba9e5d132e3df7c0a71dee7e84d97a1e@54.247.115.161:26656,9981156be9f73f5ff6219af6f5824b6eadd32c99@78.46.174.116:16656,432078f1311838ca7df64f870de5512f1648db91@70.161.39.60:26656,e7c9f745d72834b71dfe4f3ab9e1544a7667665f@109.70.113.100:26656,42f173cf91e2ed30a9ad2526a61c1bb8a5f94448@89.149.218.76:26656,69f8938f8e66ccf2dbbd1b40aa37ef66d8aaa2b3@193.29.62.183:26656,ef4ccb7b01190a68697b4562de56867b311a66a8@38.140.46.58:26656,90bed4def93414f7e47b0d8c50b595151cf02ff6@5.199.161.117:26656,3000004323520c9068570cb8ccacb1bcbf34e200@136.24.44.100:26656,c58852a0c6ee1d1a68b76e5a54a9dbce895065d9@162.55.245.149:2140
  seeds: 
  addrbook:
    enabled: true
    url: https://snapshots.polkachu.com/addrbook/akash/addrbook.json

  # Pruning configuration
  pruning: "custom"
  pruning_keep_recent: "100"
  pruning_keep_every: "0"
  pruning_interval: "10"

  iavl_disable_fastnode: true

  proxy_app: "tcp://127.0.0.1:26658"
  fast_sync: true
  db_backend: "goleveldb"
  db_dir: "data"
  log_level: "info"
  log_format: "plain"
  genesis_file: "config/genesis.json"
  priv_validator_state_file: "data/priv_validator_state.json"
  priv_validator_key_file: "config/priv_validator_key.json"
  # priv_validator_key_file: ""
  # priv_validator_laddr: "tcp://127.0.0.1:26659"
  node_key_file: "config/node_key.json"
  abci: "socket"
  filter_peers: false
  rpc:
    laddr: "tcp://127.0.0.1:26657"
    cors_allowed_origins: "[]"
    cors_allowed_methods: "['HEAD', 'GET', 'POST']"
    cors_allowed_headers: "['Origin', 'Accept', 'Content-Type', 'X-Requested-With', 'X-Server-Time']"
    grpc_laddr: ""
    grpc_max_open_connections: 900
    unsafe: false
    max_open_connections: 900
    max_subscription_clients: 100
    max_subscriptions_per_client: 5
    experimental_subscription_buffer_size: 200
    experimental_websocket_write_buffer_size: 200
    experimental_close_on_slow_client: false
    timeout_broadcast_tx_commit: "10s"
    max_body_bytes: 1000000
    max_header_bytes: 1048576
    tls_cert_file: ""
    tls_key_file: ""
    pprof_laddr: "localhost:6060"
  p2p:
    laddr: "tcp://0.0.0.0:26656"
    external_address: ""
    upnp: false
    addr_book_file: "config/addrbook.json"
    addr_book_strict: true
    max_num_inbound_peers: 40
    max_num_outbound_peers: 10
    unconditional_peer_ids: ""
    persistent_peers_max_dial_period: "0s"
    flush_throttle_timeout: "100ms"
    max_packet_msg_payload_size: 1024
    send_rate: 5120000
    recv_rate: 5120000
    pex: true
    seed_mode: false
    private_peer_ids: ""
    allow_duplicate_ip: false
    handshake_timeout: "20s"
    dial_timeout: "3s"
  mempool:
    version: "v0"
    recheck: true
    broadcast: true
    wal_dir: ""
    size: 5000
    max_txs_bytes: 1073741824
    cache_size: 10000
    keep-invalid-txs-in-cache: false
    max_tx_bytes: 1048576
    max_batch_bytes: 0
    ttl-duration: "0s"
    ttl-num-blocks: 0
  statesync:
    enable: false
    rpc_servers: ""
    trust_height: 0
    trust_hash: ""
    trust_period: "168h0m0s"
    discovery_time: "15s"
    temp_dir: ""
    chunk_request_timeout: "10s"
    chunk_fetchers: "4"
  fastsync:
    version: "v0"
  consensus:
    wal_file: "data/cs.wal/wal"
    timeout_propose: "3s"
    timeout_propose_delta: "500ms"
    timeout_prevote: "1s"
    timeout_prevote_delta: "500ms"
    timeout_precommit: "1s"
    timeout_precommit_delta: "500ms"
    timeout_commit: "5s"
    double_sign_check_height: 0
    skip_timeout_commit: false
    create_empty_blocks: true
    create_empty_blocks_interval: "0s"
    peer_gossip_sleep_duration: "100ms"
    peer_query_maj23_sleep_duration: "2s"
  storage:
    discard_abci_responses: false
  tx_index:
    indexer: "kv"
    psql-conn: ""
  instrumentation:
    prometheus: true
    prometheus_listen_addr: ":26660"
    max_open_connections: 900
    namespace: "tendermint"

  halt_height: 0
  halt_time: 0
  min_retain_blocks: 0
  inter_block_cache: true
  index_events: "[]"
  iavl_cache_size: 781250

  telemetry:
    enabled: false
    serviceName: ""
    enableHostname: false
    enableHostnameLabel: false
    enableServiceLabel: false
    prometheusRetentionTime: 0
    globalLabels: "[]"

  api:
    enable: false
    swagger: false
    address: "tcp://0.0.0.0:1317"
    maxOpenConnections: 1000
    rpcReadTimeout: 10
    rpcWriteTimeout: 0
    rpcMaxBodyBytes: 1000000
    enabledUnsafeCors: false

  rosetta:
    enable: false
    address: ":8080"
    blockchain: "app"
    network: "network"
    retries: 3
    offline: false

  grpc:
    enable: true
    address: "0.0.0.0:9090"
  grpcWeb:
    enable: true
    address: "0.0.0.0:9091"
    enableUnsafeCors: false
  stateSync:
    snapshotInterval: 0
    snapshotKeepRecent: 2

# If your node gets connection troubles to Polkachu,
# make sure to get through the trouble-shooting section at
# https://polkachu.com/state_sync/akash
state_sync:
  enabled: false
  rpc1: "https://akash-rpc.polkachu.com:443"
  rpc2: "https://akash-rpc.polkachu.com:443"
  node_id: ""
  # height_offset should equal the AKASH_STATE_SYNC_SNAPSHOT_INTERVAL on the node which makes the state-sync snapshots
  height_offset: 2000

snapshots:
  enabled: false

microk8s:
  enabled: true
  hostpath: /data/akash-validator

# Used for mounting AKASH_HOME on a specific node
local_storage:
  enabled: false
  capacity: 100Gi
  path: /data/akash-validator
  host: ""

# If the node is a validator
validator:
  enabled: true
  tmkms: false
  node_key: ""
  priv_key: ""

# If the node is a fullnode (non-validator)
fullnode:
  enabled: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  tls: false
  domain: "dmain.tld"
  grpc:
    enabled: false
    tls: false
