{{- if .Values.validator.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: node-key
  namespace: {{ .Release.Namespace }}
type: "Opaque"
data:
  node_key.json: {{ .Values.validator.node_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: priv-validator-key
  namespace: {{ .Release.Namespace }}
type: "Opaque"
data:
  priv_validator_key.json: {{ .Values.validator.priv_key }}
{{- end }}