ingress:
  enabled: true
  hostname: example.com

image:
  repository: ghcr.io/blockpane/tenderduty
  tag: v2.2.1
  pullPolicy: Always
enable_dashboard: yes
listen_port: 8888
hide_logs: yes
node_down_alert_minutes: 3
node_down_alert_severity: critical
prometheus_enabled: yes
prometheus_listen_port: 28686

# Alerting settings
pagerduty:
  enabled: no
  api_key: aaaaaaaaaaaabbbbbbbbbbbbbcccccccccccc
  default_severity: alert
discord:
  enabled: no
  webhook: https://discord.com/api/webhooks/999999999999999999/zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
telegram:
  enabled: no
  api_key: '5555555555:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
  channel: "-666666666"
slack:
  enabled: no
  webhook: https://hooks.slack.com/services/AAAAAAAAAAAAAAAAAAAAAAA/bbbbbbbbbbbbbbbbbbbbbbbb

chains:
  Osmosis:
    chain_id: osmosis-1
    valoper_address: osmovaloper16q8xd335y38xk2ul67mjg27vdnrcnklt4wx6kt
    public_fallback: yes
    alerts:
      consecutive_enabled: yes
      consecutive_missed: 1000
      pagerduty:
        enabled: no
    nodes:
      - url: https://osmosis-rpc.lavenderfive.com:443
  Akash:
    chain_id: akashnet-2
    valoper_address: akashvaloper1dgxdep80th2qm8xxk8h3j3g93npsd3a8jg60gz
    public_fallback: yes
    alerts:
      consecutive_enabled: yes
      consecutive_missed: 1000
      pagerduty:
        enabled: no
    nodes:
      - url: https://rpc.akash.forbole.com:443
