{{- if .Values.local_storage.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: injective-node-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: injective-local-storage
  resources:
    requests:
      storage: {{ $.Values.local_storage.capacity }}
{{- end }}