{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cosmos-endpoint-cache.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    {{ if .Values.rpcCache.enabled }}
    - host: {{ .Values.ingress.chain }}.rpc.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cosmos-endpoint-cache.fullname" . }}
                port:
                  number: 5001
    {{- end }}
    {{ if .Values.restApiCache.enabled }}
    - host: {{ .Values.ingress.chain }}.api.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cosmos-endpoint-cache.fullname" . }}
                port:
                  number: 5000
    {{- end }}
{{- end }}
