{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cosmos-endpoint-cache.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
  {{- if .Values.restApiCache.enabled }}
  - hosts:
    - api.{{ .Values.ingress.chain }}.{{ .Values.ingress.domain }}
    secretName: cosmoshub-api-tls
  {{- end }}
  {{- if .Values.rpcCache.enabled }}
  - hosts:
    - rpc.{{ .Values.ingress.chain }}.{{ .Values.ingress.domain }}
    secretName: cosmoshub-rpc-tls
  {{- end }}
  {{- end }}
  rules:
    {{- if .Values.rpcCache.enabled }}
    - host: rpc.{{ .Values.ingress.chain }}.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cosmos-endpoint-cache.fullname" . }}
                port:
                  number: 5001
    {{- end }}
    {{- if .Values.rpcCache.rpcWebsocketEnabled }}
    - host: rpc.{{ .Values.ingress.chain }}.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /websocket
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.rpcCache.rpcWebsocketServiceName }}
                port:
                  number: {{ .Values.rpcCache.rpcWebsocketServicePort }}
    {{- end }}
    {{- if .Values.restApiCache.enabled }}
    - host: api.{{ .Values.ingress.chain }}.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cosmos-endpoint-cache.fullname" . }}
                port:
                  number: 5000
    {{- end }}
    {{- if .Values.grpc.enabled }}
    - host: grpc.{{ .Values.ingress.chain }}.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.rpcCache.rpcWebsocketServiceName }}
                port:
                  number: {{ .Values.grpc.port }}
    {{- end }}
{{- end }}
