apiVersion: v1
kind: Service
metadata:
  name: {{ include "cosmos-endpoint-cache.fullname" . }}
  labels:
    {{- include "cosmos-endpoint-cache.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.rpcCache.enabled }}
    - port: {{ .Values.rpcCache.port }}
      targetPort: {{ .Values.rpcCache.port }}
      protocol: TCP
      name: rpc
    {{- end }}
    {{- if .Values.restApiCache.enabled }}
    - port: {{ .Values.restApiCache.port }}
      targetPort: {{ .Values.restApiCache.port }}
      protocol: TCP
      name: rest
    {{- end }}
  selector:
    {{- include "cosmos-endpoint-cache.selectorLabels" . | nindent 4 }}
