---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  {{- if .Values.validator.enabled }}
  name: dydxprotocol-node-validator
  {{- else }}
  name: dydxprotocol-fullnode
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- if .Values.validator.enabled }}
    app: dydxprotocol-validator
    dydxprotocol.network/validator: "{{ .Values.dydxprotocol_node.moniker }}"
  {{- else }}
    app: dydxprotocol-fullnode
    dydxprotocol.network/fullnode: "{{ .Values.dydxprotocol_node.moniker }}"
  {{- end }}
spec:
  replicas: 1
  {{- if .Values.validator.enabled }}
  serviceName: dydxprotocol-validator
  {{- else }}
  serviceName: dydxprotocol-fullnode
  {{- end }}
  selector:
    matchLabels:
    {{- if .Values.validator.enabled }}
      app: dydxprotocol-validator
      dydxprotocol.network/validator: "{{ .Values.dydxprotocol_node.moniker }}"
    {{- else }}
      app: dydxprotocol-fullnode
      dydxprotocol.network/fullnode: "{{ .Values.dydxprotocol_node.moniker }}"
    {{- end }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
      {{- if .Values.validator.enabled }}
        app: dydxprotocol-validator
        dydxprotocol.network/validator: "{{ .Values.dydxprotocol_node.moniker }}"
      {{- else }}
        app: dydxprotocol-fullnode
        dydxprotocol.network/fullnode: "{{ .Values.dydxprotocol_node.moniker }}"
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- if .Values.validator.enabled }}
      serviceAccountName: dydxprotocol-validator
    {{- else }}
      ServiceAccountName: dydxprotocol-fullnode
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.local_storage.enabled }}
      nodeSelector:
        kubernetes.io/hostname: {{ $.Values.local_storage.host }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: [ "/bin/dydxprotocold" , "start" ]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DYDX_MONIKER
              value: {{ .Values.dydxprotocol_node.moniker }}
            - name: DYDX_NET
              value: {{ .Values.dydxprotocol_node.net }}
            - name: DYDX_HOME
              value: {{ .Values.home }}
            - name: DYDX_CHAIN_ID
              value: {{ .Values.dydxprotocol_node.chainid }}
            - name: DYDX_KEYRING_BACKEND
              value: {{ .Values.keyring_backend }}
            {{- if .Values.state_sync.enabled }}
            - name: DYDX_P2P_PERSISTENT_PEERS
              value: {{ .Values.dydxprotocol_node.peers }},{{ .Values.state_sync.node_id }}
            {{- else if not .Values.dydxprotocol_node.addrbook.enabled }}
            - name: DYDX_P2P_PERSISTENT_PEERS
              value: {{ .Values.dydxprotocol_node.peers }}
            {{- end }}
            {{- if .Values.snapshots.enabled }}
            - name: DYDX_STATE_SYNC_SNAPSHOT_INTERVAL
              value: "2000"
            - name: DYDX_STATE_SYNC_SNAPSHOT_KEEP_RECENT
              value: "5"
            - name: DYDX_PRUNING
              value: "custom"
            - name: DYDX_PRUNING_KEEP_RECENT
              value: "100"
            - name: DYDX_PRUNING_KEEP_EVERY
              value: "2000"
            - name: DYDX_PRUNING_INTERVAL
              value: "10"
            {{- else }}
            - name: DYDX_PRUNING
              value: "{{ .Values.dydxprotocol_node.pruning }}"
            - name: DYDX_PRUNING_KEEP_RECENT
              value: "{{ .Values.dydxprotocol_node.pruning_keep_recent }}"
            - name: DYDX_PRUNING_KEEP_EVERY
              value: "{{ .Values.dydxprotocol_node.pruning_keep_every }}"
            - name: DYDX_PRUNING_INTERVAL
              value: "{{ .Values.dydxprotocol_node.pruning_interval }}"
            {{- end }}
            - name: DYDX_IAVL_DISABLE_FASTNODE
              value: "{{ .Values.dydxprotocol_node.iavl_disable_fastnode }}"
            - name: DYDX_P2P_LADDR
              value: tcp://0.0.0.0:26656
            - name: DYDX_RPC_LADDR
              value: tcp://0.0.0.0:26657
            - name: DYDX_RPC_PPROF_LADDR
              value: 0.0.0.0:6060
            - name: DYDX_GRPC_ADDRESS
              value: 0.0.0.0:9090
            - name: DYDX_P2P_ADDR_BOOK_STRICT
              value: "false"
            - name: DYDX_ROSETTA_ENABLE
              value: "false"
            - name: DYDX_P2P_SEED_MODE
              value: "true"
            - name: DYDX_P2P_PEX
              value: "{{ .Values.dydxprotocol_node.p2p.pex }}"
            - name: DYDX_DEBUG
              value: "{{ $.Values.debug }}"
            - name: DYDX_MINIMUM_GAS_PRICES
              value: "{{ .Values.dydxprotocol_node.minimum_gas_prices }}"
            - name: SNAPSHOT_PROVIDER
              value: "{{ .Values.dydxprotocol_node.snapshot_provider }}"
            {{- if .Values.state_sync.enabled }}
            - name: DYDX_STATESYNC_ENABLE
              value: "true"
            - name: DYDX_STATESYNC_RPC_SERVERS
              value: "{{ .Values.state_sync.rpc1 }},{{ .Values.state_sync.rpc2 }}"
            {{- end }}
            - name: DYDX_API_ENABLE
              value: "{{ .Values.dydxprotocol_node.api_enable }}"
          ports:
            - containerPort: 1317
              name: api
            - containerPort: 26656
              name: p2p
            - containerPort: 26657
              name: rpc
            - containerPort: 26660
              name: metrics
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            {{- if .Values.validator.enabled }}
            - name: dydxprotocol-validator-config-toml
            {{- else }}
            - name: dydxprotocol-fullnode-config-toml
            {{- end }}
              mountPath: /root/.dydxprotocol/config/config.toml
              subPath: config.toml
            {{- if .Values.validator.enabled }}
            - name: dydxprotocol-validator-app-toml
            {{- else }}
            - name: dydxprotocol-fullnode-app-toml
            {{- end }}
              mountPath: /root/.dydxprotocol/config/app.toml
              subPath: app.toml
            - name: dydxprotocol-pricefeed-exchange-toml
              mountPath: /root/.dydxprotocol/config/pricefeed_exchange_config.toml
              subPath: pricefeed_exchange_config.toml
          {{- if .Values.local_storage.enabled }}
            - name: local-persistent-storage
              mountPath: "{{ .Values.home }}"
          {{- else }}
            - name: home
              mountPath: "{{ .Values.home }}"
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: dydxprotocol-node-config
        {{- if .Values.validator.enabled }}
        - name: dydxprotocol-validator-config-toml
          configMap:
            name: dydxprotocol-validator-config-toml
        {{- else }}
        - name: dydxprotocol-fullnode-config-toml
          configMap:
            name: dydxprotocol-fullnode-config-toml
        {{- end }}
        {{- if .Values.validator.enabled }}
        - name: dydxprotocol-validator-app-toml
          configMap:
            name: dydxprotocol-validator-app-toml
        {{- else }}
        - name: dydxprotocol-fullnode-app-toml
          configMap:
            name: dydxprotocol-fullnode-app-toml
        {{- end }}
        - name: dydxprotocol-pricefeed-exchange-toml
          configMap:
            name: dydxprotocol-pricefeed-exchange-toml
      {{- if .Values.microk8s.enabled }}
        - name: home
          hostPath:
            # Ensure the file directory is created.
            path: "{{ .Values.microk8s.hostpath }}"
            type: DirectoryOrCreate
      {{- end }}
