{{- if .Values.validator.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: assetmantle-validator
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - port: 1317
    targetPort: 1317
    protocol: TCP
    name: api
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: grpc
  - port: 26656
    targetPort: 26656
    protocol: TCP
    name: p2p
  - port: 26657
    targetPort: 26657
    protocol: TCP
    name: rpc
  selector:
    app: "assetmantle-validator"
{{- else }}
---
apiVersion: v1
kind: Service
metadata:
  name: assetmantle-fullnode
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - port: 1317
    targetPort: 1317
    protocol: TCP
    name: api
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: grpc
  - port: 26656
    targetPort: 26656
    protocol: TCP
    name: p2p
  - port: 26657
    targetPort: 26657
    protocol: TCP
    name: rpc
  selector:
    assetmantle.network/fullnode: "{{ .Values.assetmantle_node.moniker }}"
{{- end }}
