# Default values for dydx-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "ghcr.io/charlesjudith/dydxprotocol-docker"
  tag: "v0.4.0"
  pullPolicy: IfNotPresent

# Common Values

keyring_backend: "os"
home: "/root/.dydxprotocol"
debug: "false"

# Set Values to run a single dydx node connected to an existing network
# Defaults to mainnet
dydxprotocol_node:
  api_enable: "true"
  moniker: StakeLab
  chainid: dydx-testnet-4
  # disable PEX when nodes have issues with syncing / catching up / peer dial errors/flood
  minimum_gas_prices: "0.025ibc/8E27BA2D5493AF5636760E354E46004562C46AB7EC0CC4C1CA14E9E20E2545B5,25000000000adv4tnt"
  net: https://raw.githubusercontent.com/CharlesJUDITH/dydxprotocol-docker/main/genesis.json
  peers: 9295f3740108f618d5fe0ec8ba3c6b0cb0d728d7@199.254.199.241:26656,5ccb5f270766c06a80ad08aa59814e6622bc8d51@165.22.73.158:26656,a60322bd581703b19000a81f9dbf326b52e2fbbd@13.114.96.36:26656,47817889aece4dd89753173a3e4d1ee8daeb4898@45.32.36.82:26656,d812c7c0a5b4c4e9229c706241c0aa9a44e09378@104.156.238.56:26656,57b568621e727e87a3c29ce476865599c3db6e11@141.94.98.35:26656,c213a37157c08e2920bebf0eaee81713deed938f@20.41.104.10:26656,35d4dbc5edcb96f772c33c05fdd20885ebdcb7fb@143.244.33.37:31627,c250b2e59f2cb3e9938692c4475563ec9ffaa3d2@15.235.204.15:26656,9c506dcbd413e86031450befdf052ab44cf43dc7@139.180.141.248:55836,27623a574fabf63dc0ea5cb1a294523c17c6d36e@188.42.220.52:26656,76944deb472e6c6b4b73bff73fb3b9a164b89fa4@185.119.116.241:26656,38e5a5ec34c578dc323cbdd9b98330abb448d586@tenderseed.ccvalidators.com:29104,9ff4162e3f6dd8999caa0f57209210c3ef827e76@dydx-p2p-val.enigma-validator.com:3090,481637ea7bc3244f435f17682fd0d18355fae25c@194.233.95.115:26656,47cb90109f169ac4a18154b16517d38c19830773@85.207.33.82:26656,55b8e1fa0b6e8d746cbb84005fa53dc1a2b0f9c9@103.106.228.57:26656,62230535360e25317617e48d4fdcae911d02565c@35.206.155.207:26656,6cb20034ced7b4064e24fb54a2bb5d245031d778@195.14.6.184:26656,2dd274958555371b4a7a77b23b4313d8da45ca07@167.71.218.117:26656,f4d7fb6f806f93b6addadf68935ff17765805d2e@199.254.199.243:26656
  seeds: 19d38bb5cea1378db3e16615e63594dc26119a1a@dydx-testnet4-seednode.allthatnode.com:26656,38e5a5ec34c578dc323cbdd9b98330abb448d586@tenderseed.ccvalidators.com:29104,80a1a6cd086634c34008c6457d3f7441cfc05c47@seeds.kingnodes.com:27056,20e1000e88125698264454a884812746c2eb4807@seeds.lavenderfive.com:23856,87ee8de5f0f82af6ee6740a30f8844bbe6434413@seed.dydx-testnet.cros-nest.com:26656,182ab0015fb4b7d751b12a9c0162ac123445eac1@seed.dydx-testnet.stakingcabin.com:26656,76b472b107ccf20c3d6c110c4a2a217306d2dedb@dydx-seed.staker.space:26656,edd6d0eefb14a93cad9bc7edd0b8b7e697c9d32f@dydx-testnet-4.notional.ventures:2130
  addrbook:
    enabled: false
    url: 

  liquidationDaemonLoopDelayMs: 1600
  liquidationDaemonEnable: true
  # Pruning configuration
  pruning: "custom"
  pruning_keep_recent: "100"
  pruning_keep_every: "0"
  pruning_interval: "10"

  iavl_disable_fastnode: true

  proxy_app: "tcp://127.0.0.1:26658"
  block_sync: true
  db_backend: "goleveldb"
  db_dir: "data"
  log_level: "info"
  log_format: "plain"
  genesis_file: "config/genesis.json"
  priv_validator_state_file: "data/priv_validator_state.json"
  priv_validator_key_file: "config/priv_validator_key.json"
  node_key_file: "config/node_key.json"
  abci: "socket"
  filter_peers: false
  rpc:
    laddr: "tcp://0.0.0.0:26657"
    cors_allowed_origins: "[*, ]"
    cors_allowed_methods: "['HEAD', 'GET', 'POST']"
    cors_allowed_headers: "['Origin', 'Accept', 'Content-Type', 'X-Requested-With', 'X-Server-Time']"
    grpc_laddr: ""
    grpc_max_open_connections: 900
    unsafe: false
    max_open_connections: 900
    max_subscription_clients: 100
    max_subscriptions_per_client: 5
    experimental_subscription_buffer_size: 200
    experimental_websocket_write_buffer_size: 200
    experimental_close_on_slow_client: false
    timeout_broadcast_tx_commit: "10s"
    max_body_bytes: 1000000
    max_header_bytes: 1048576
    tls_cert_file: ""
    tls_key_file: ""
    pprof_laddr: "localhost:6060"
  p2p:
    laddr: "tcp://0.0.0.0:26656"
    external_address: ""
    upnp: false
    addr_book_file: "config/addrbook.json"
    addr_book_strict: true
    max_num_inbound_peers: 40
    max_num_outbound_peers: 10
    unconditional_peer_ids: ""
    persistent_peers_max_dial_period: "0s"
    flush_throttle_timeout: "100ms"
    max_packet_msg_payload_size: 1024
    send_rate: 5120000
    recv_rate: 5120000
    pex: true
    seed_mode: false
    private_peer_ids: ""
    allow_duplicate_ip: false
    handshake_timeout: "20s"
    dial_timeout: "3s"
  mempool:
    version: "v1"
    recheck: true
    broadcast: true
    wal_dir: ""
    size: 5000
    max_txs_bytes: 1073741824
    cache_size: 20000
    keep-invalid-txs-in-cache: true
    max_tx_bytes: 1048576
    max_batch_bytes: 0
    ttl-duration: "0s"
    ttl-num-blocks: 20
    max_txs: 5000
  statesync:
    enable: false
    rpc_servers: "https://dydx-testnet-rpc.polkachu.com:443"
    trust_height: 0
    trust_hash: ""
    trust_period: "168h0m0s"
    discovery_time: "15s"
    temp_dir: ""
    chunk_request_timeout: "10s"
    chunk_fetchers: "4"
  blocksync:
    version: "v0"
  consensus:
    wal_file: "data/cs.wal/wal"
    timeout_propose: "3s"
    timeout_propose_delta: "500ms"
    timeout_prevote: "1s"
    timeout_prevote_delta: "500ms"
    timeout_precommit: "1s"
    timeout_precommit_delta: "500ms"
    timeout_commit: "500ms"
    double_sign_check_height: 0
    skip_timeout_commit: false
    create_empty_blocks: true
    create_empty_blocks_interval: "0s"
    peer_gossip_sleep_duration: "100ms"
    peer_query_maj23_sleep_duration: "2s"
  storage:
    discard_abci_responses: false
  tx_index:
    indexer: "kv"
    psql-conn: ""
  instrumentation:
    prometheus: true
    prometheus_listen_addr: ":26660"
    max_open_connections: 900
    namespace: "cometbft"

  halt_height: 0
  halt_time: 0
  min_retain_blocks: 0
  inter_block_cache: true
  index_events: "[]"
  iavl_cache_size: 781250
  iavl-disable-fastnode: false
  iavl_lazy_loading: false
  app_db_backend: ""

  telemetry:
    enabled: true
    serviceName: ""
    enableHostname: false
    enableHostnameLabel: false
    enableServiceLabel: false
    prometheusRetentionTime: 60
    globalLabels: "[]"

  api:
    enable: true
    swagger: false
    address: "tcp://0.0.0.0:1317"
    maxOpenConnections: 1000
    rpcReadTimeout: 10
    rpcWriteTimeout: 0
    rpcMaxBodyBytes: 1000000
    enabledUnsafeCors: false

  rosetta:
    enable: false
    address: ":8080"
    blockchain: "app"
    network: "network"
    retries: 3
    offline: false
    enable_fee_suggestion: false
    gas_to_suggest: 200000
    denom_to_suggest: "uatom"

  grpc:
    enable: true
    address: "0.0.0.0:9090"
    max_recv_msg_size: "10485760"
    max_send_msg_size: "2147483647"
  grpcWeb:
    enable: true
    address: "0.0.0.0:9091"
    enableUnsafeCors: false
  stateSync:
    snapshotInterval: 0
    snapshotKeepRecent: 2

  store:
    streamers: "[]"
  streamers:
    file:
      keys: "['*', ]"
      writeDir: ""
      prefix: ""
      outputMetadata: true
      stopNodeOnError: true
      fsync: false

state_sync:
  enabled: false
  rpc1: ""
  node_id: ""
  # height_offset should equal the DYDX_STATE_SYNC_SNAPSHOT_INTERVAL on the node which makes the state-sync snapshots
  height_offset: 2000

snapshots:
  enabled: false

microk8s:
  enabled: true
  hostpath: /data/dydx-validator

# Used for mounting DYDX_HOME on a specific node
local_storage:
  enabled: false
  capacity: 100Gi
  path: /data/dydx-validator
  host: ""

ethRpcEndpoint: "https://rpc-sepolia.rockx.com"

# If the node is a validator
validator:
  enabled: true
  node_key: ""
  priv_key: ""
  tmkms: false

# If the node is a fullnode (non-validator)
fullnode:
  enabled: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  domain: "domain.tld"
  tls: false

service:
  type: LoadBalancer
  loadBalancerIP: 65.109.112.162
  p2p: 26656
  rpc: 26657
  grpc: 9090
  rest: 1317
