# Default values for axelar-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # ghcr.io/charlesjudith/axelar-docker:v0.34.0
  repository: "ghcr.io/charlesjudith/axelar-docker"
  tag: "v0.34.0"
  pullPolicy: IfNotPresent

# Common Values

keyring_backend: "test"
home: "/root/.axelar"
debug: "false"

# Set Values to run a single axelar node connected to an existing network
# Defaults to mainnet
axelar_node:
  # snapshot_provider can be either "polkachu" (2Gi), "autostake" (1Gi). Otherwise it'll default to a much larger in size.
  snapshot_provider: "polkachu"
  api_enable: "false"
  moniker: yourminikerhere
  # axelar-testnet-lisbon-3 for testnet
  chainid: axelar-dojo-1
  # disable PEX when nodes have issues with syncing / catching up / peer dial errors/flood
  minimum_gas_prices: 0.007uaxl
  net: https://snapshots.polkachu.com/genesis/axelar/genesis.json
  peers: a7b306b6421a0b474a0413905ffcae780d398ecd@65.108.232.134:53656,ba42a38d5fabc3adfe1693543892a43baec798bf@89.117.52.159:26656,82bd25371c9b90c2b778533b6d18c1092642af4d@65.21.138.124:26656,75c35e5d20c500b3d8c63f9b585a73dc67bf5c1a@51.195.5.215:26656,c57a5a356aee249e782053a410ad1ec28b554e3e@164.92.105.35:31980,0b23370fdf88131d45f7c97cf4d52c3fa73e5a4b@18.217.111.172:26656,c8d0d62f64e19299b0653c866c1962fa48d0571e@18.217.111.172:26656,1bd70c7160343fca2bb7ab81973270752f0fee30@65.109.88.96:26156,5cc4ef39a36859eccaf43274160df61d7750c491@65.108.200.124:26656,58fbeb88cc00fbb730422f561af0cded7c30dcf6@135.181.142.60:15609,2362c26b7add662783c5dc26b4c8d153646f825b@3.142.113.84:26656,9a7200e587d99c030a099cd042f8c3343651bc25@18.217.111.172:26656,9425008c07a9e2bd06c86355dd5b4869c2c14ba0@13.59.129.55:26656,c9cd16fe16eb8fa9ad0dc5fbde23874009bec674@3.142.113.84:26656,b14a646e069dec33cc52084f79c01336b6b759f1@3.142.113.84:26656,eeef7f201b6a2b7ebb1af3037bb9022d3dc40372@13.59.129.55:26656,923c34e41b9bcdc8e4d407213b274c1a0d5b6d30@52.73.168.104:26656,977ff6924eff671c59b0727db0e16ec9bac159fb@18.217.111.172:26656,99ed04bcbbbef0b668b99a722a47716e2b3625e6@142.132.248.38:26656,4f12f80da0eda26c77f2780f755cea498198f8cd@3.142.113.84:26656,051a6fe084df02c6a4c484139899808eea841181@13.59.129.55:26656,08fcce0c1b1d2a29040cabab02e2fb279e3ec52d@3.134.227.58:26656,df8458f018d16dd0cb5dfa08005cf4421fa028b6@3.142.113.84:26656,1136202f40f158b6e11257af1a34ce5379179d05@3.142.113.84:26656,353f7d0962594bcbfb63c81594e35e39c4c89a1a@18.217.111.172:26656,2f3277dcf83378a0454b802cbf8b93d777154b72@135.181.138.95:12010,43d1978a039a3d50d826e0b30d2f1d592284ce57@135.148.169.22:26656,49762b752c9fd10e7eefa323ce53b0a731920520@138.201.36.98:26657,d1d9761737f3008bfa6e48f356ea4f40073ef4da@84.244.95.227:26656,6a3d694253238f83dfa4329fcd89a4ff1870dd1b@18.217.111.172:26656,54e0c474ba49b1e78b09c9eff1a39ca3214c65a8@185.163.64.143:26656,d80d8b31cb6ce5fcace42284fa6bbcab446670f7@195.201.175.156:15156,f276e9620dc42021e91a285196a10c2f0fe2a510@3.142.113.84:26656,00b800626fb3c6e1d28a460d151220644cec25d1@13.59.129.55:26656,ee2c09a07247648d6baf38475619e09ea11e910a@95.216.73.247:15156,f8ab212377af0b4468171951811e4401e66a0c36@51.91.152.102:30005,6a82e71dd2e90a1b89d6ead3e2759519a815f975@13.59.129.55:26656,5581d7215b95264e600209bfed0fa28a305620dd@18.217.111.172:26656,9cf4e948a4490a413154c5ebd7ba1c382577ee9d@35.228.251.58:26656,fc08e2e9b1ffd5941a07896a8b79cf85db5e8da9@13.59.129.55:26656,41a950fe30bb90c57729c02ea1272779691b4233@65.108.230.188:15156,a6aa863e4ec19c8f35e5fb705d8b4b7506a0fbcc@15.235.53.184:26656,1f34c956e2e36e5eeae1fc4ec6bea65c649c8a02@51.81.49.132:15156,543b2b5503106b6506a99f983b3ad899e4fdf4f2@178.23.126.83:26656,d80a505b12a5f492a349a87f348e8ddd311ca2ba@34.75.115.166:26656,6afa1809697c42bb526b3aa7be6de71165d936c3@5.78.66.134:26656,7136c52148b37f2cbc182be9c93c93ef89e54c81@46.4.91.49:31656,e23b7b45d4deb94aa64f14b16dbbd3c4d2d7ce51@51.222.241.200:26656,6ebdf8caf73440a968efe993648d3de396422776@13.59.129.55:26656
  seeds:
  addrbook:
    enabled: true
    url: https://snapshots.polkachu.com/addrbook/axelar/addrbook.json

  # Pruning configuration
  pruning: "custom"
  pruning_keep_recent: "100"
  pruning_keep_every: "0"
  pruning_interval: "10"

  iavl_disable_fastnode: true

  proxy_app: "tcp://127.0.0.1:26658"
  fast_sync: true
  db_backend: "goleveldb"
  db_dir: "data"
  log_level: "info"
  log_format: "plain"
  genesis_file: "config/genesis.json"
  priv_validator_state_file: "data/priv_validator_state.json"
  priv_validator_key_file: "config/priv_validator_key.json"
  # priv_validator_key_file: ""
  # priv_validator_laddr: "tcp://127.0.0.1:26659"
  node_key_file: "config/node_key.json"
  abci: "socket"
  filter_peers: false
  rpc:
    laddr: "tcp://0.0.0.0:26657"
    cors_allowed_origins: "[]"
    cors_allowed_methods: "['HEAD', 'GET', 'POST']"
    cors_allowed_headers: "['Origin', 'Accept', 'Content-Type', 'X-Requested-With', 'X-Server-Time']"
    grpc_laddr: ""
    grpc_max_open_connections: 900
    unsafe: false
    max_open_connections: 900
    max_subscription_clients: 100
    max_subscriptions_per_client: 5
    experimental_subscription_buffer_size: 200
    experimental_websocket_write_buffer_size: 200
    experimental_close_on_slow_client: false
    timeout_broadcast_tx_commit: "10s"
    max_body_bytes: 1000000
    max_header_bytes: 1048576
    tls_cert_file: ""
    tls_key_file: ""
    pprof_laddr: "localhost:6060"
  p2p:
    laddr: "tcp://0.0.0.0:26656"
    external_address: ""
    upnp: false
    addr_book_file: "config/addrbook.json"
    addr_book_strict: true
    max_num_inbound_peers: 240
    max_num_outbound_peers: 30
    unconditional_peer_ids: ""
    persistent_peers_max_dial_period: "0s"
    flush_throttle_timeout: "100ms"
    max_packet_msg_payload_size: 1024
    send_rate: 5120000
    recv_rate: 5120000
    pex: true
    seed_mode: false
    private_peer_ids: ""
    allow_duplicate_ip: false
    handshake_timeout: "20s"
    dial_timeout: "3s"
  mempool:
    version: "v0"
    recheck: true
    broadcast: true
    wal_dir: ""
    size: 10000
    max_txs_bytes: 1073741824
    cache_size: 10000
    keep-invalid-txs-in-cache: false
    max_tx_bytes: 1048576
    max_batch_bytes: 0
    ttl-duration: "0s"
    ttl-num-blocks: 0
  statesync:
    enable: false
    rpc_servers: ""
    trust_height: 0
    trust_hash: ""
    trust_period: "112h0m0s"
    discovery_time: "15s"
    temp_dir: ""
    chunk_request_timeout: "10s"
    chunk_fetchers: "4"
  blocksync:
    version: "v0"
  consensus:
    wal_file: "data/cs.wal/wal"
    timeout_propose: "3s"
    timeout_propose_delta: "500ms"
    timeout_prevote: "1s"
    timeout_prevote_delta: "500ms"
    timeout_precommit: "1s"
    timeout_precommit_delta: "500ms"
    timeout_commit: "3s"
    double_sign_check_height: 0
    skip_timeout_commit: false
    create_empty_blocks: true
    create_empty_blocks_interval: "0s"
    peer_gossip_sleep_duration: "100ms"
    peer_query_maj23_sleep_duration: "2s"
  storage:
    discard_abci_responses: false
  tx_index:
    indexer: "kv"
    psql-conn: ""
  instrumentation:
    prometheus: true
    prometheus_listen_addr: ":26660"
    max_open_connections: 900
    namespace: "tendermint"

  halt_height: 0
  halt_time: 0
  min_retain_blocks: 0
  inter_block_cache: true
  index_events: "[]"
  iavl_cache_size: 781250

  telemetry:
    enabled: false
    serviceName: ""
    enableHostname: false
    enableHostnameLabel: false
    enableServiceLabel: false
    prometheusRetentionTime: 0
    globalLabels: "[]"

  api:
    enable: true
    swagger: false
    address: "tcp://0.0.0.0:1317"
    maxOpenConnections: 1000
    rpcReadTimeout: 10
    rpcWriteTimeout: 0
    rpcMaxBodyBytes: 1000000
    enabledUnsafeCors: false

  rosetta:
    enable: false
    address: ":8080"
    blockchain: "app"
    network: "network"
    retries: 3
    offline: false

  grpc:
    enable: true
    address: "0.0.0.0:9090"
  grpcWeb:
    enable: true
    address: "0.0.0.0:9091"
    enableUnsafeCors: false
  stateSync:
    snapshotInterval: 0
    snapshotKeepRecent: 2

state_sync:
  enabled: false
  rpc1: "https://axelar-rpc.polkachu.com:443"
  node_id: ""
  # height_offset should equal the AXELAR_STATE_SYNC_SNAPSHOT_INTERVAL on the node which makes the state-sync snapshots
  height_offset: 2000

snapshots:
  enabled: false

microk8s:
  enabled: true
  hostpath: /data/axelar-validator

# Used for mounting AXELAR_HOME on a specific node
local_storage:
  enabled: false
  capacity: 100Gi
  path: /data/axelar-validator
  host: ""

# If the node is a validator
validator:
  enabled: true
  node_key: ""
  priv_key: ""
  tmkms: false
  
# If the node is a fullnode (non-validator)
fullnode:
  enabled: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  domain: "domain.tld"
  tls: false
  annotations:
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"