# Default values for chihuahua-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # repository: ghcr.io/charlesjudith/chihuahua-node-docker
  repository: "ghcr.io/akash-network/cosmos-omnibus"
  tag: "v0.3.32-chihuahua-v4.2.3"
  pullPolicy: IfNotPresent

# Common Values

keyring_backend: "test"
home: "/root/.chihuahuad"
debug: "false"

# Set Values to run a single chihuahua node connected to an existing network
# Defaults to mainnet
chihuahua_node:
  # snapshot_provider can be either "polkachu" (2Gi), "autostake" (1Gi). Otherwise it'll default to a much larger in size.
  snapshot_provider: "polkachu"
  api_enable: "false"
  moniker: yourminikerhere
  chainid: chihuahua-1
  # disable PEX when nodes have issues with syncing / catching up / peer dial errors/flood
  minimum_gas_prices: 1uhuahua
  net: https://raw.githubusercontent.com/ChihuahuaChain/chihuahua/main/mainnet
  peers: f01a0195f6e00e4384be16950a50f677c9abc60d@193.70.45.106:12956,a9dff4b2b5232b0513f1214e1f8104284f2cc327@85.239.233.56:2000,62af33efd5bf492038baff03bdc7924dd7528a10@155.133.22.8:23356,b212d5740b2e11e54f56b072dc13b6134650cfb5@169.155.45.138:26656,2e1e9ccd68c1f25016168fc050aed900b553fdb0@185.242.112.32:56646,16b233ebedd6a88ba298f37cbe8a9fb2e6358fa5@135.181.215.62:3440,a13b0de5c0d520d927f426730018bb7ab5b31de9@130.193.58.105:26656,865ce49df169de9aa0e9530ed3a9a22435c0fc13@213.239.214.73:6095,f924bd81748ec9aa8ac6b2f976bb0c4d477d685d@95.214.55.210:26656,b90228e67cf53c0856d035f5572c4145038d1226@15.204.198.82:26656,015506eb1e6599a9a204fdd12ad66ab098011d1d@104.131.31.5:26656,dc5b51a337b6467e568f255ef0b5d52872edd05a@95.216.144.130:26656,acfd8c6af6b3ecbe729ebecc6e30f0c850f20ede@65.108.238.102:12956,5782e3d676bab446ae564014d42ff7159e3400a2@138.201.197.119:3000,d542a7b1798285c7d2dd58defbe5cddc811bdc75@138.68.40.251:26656,68058533c09829404d56a41c3f122c86f6f9af45@141.94.219.133:10556,0f97f82883b409652a2b23ba8c2e05d5d85aa530@73.190.98.73:26656,814666cbfd8d160bfcd54568ee5322d643527b1a@85.237.193.109:26656,323737e89b2119861c9015e5b9a06d8f52b2bd37@83.149.102.56:6095,f0266cd6868233b94e94c986cca8fce5ee16246e@65.108.126.215:26656,c2ef001f240ba7951a0bf851e5be6975382ca683@198.244.179.233:26656,2faf86d3587c1f6ee4cfce8434a6b5ef61e54c21@65.21.228.161:2000,e1b058e5cfa2b836ddaa496b10911da62dcf182e@138.201.8.248:26656,aa30ee7e94ac37b86edad53c32a65df74dc2bad8@95.217.41.162:26656,121348a569f2ad5e707dafcd08803f7d4b68d66f@65.108.78.249:26756,176d693106948f3a5e27bd4c45e4d71d71513be4@104.193.254.115:26656,dde6d562c36d78fa2e3e4d62cde94a99c43f2c25@65.109.89.19:12956,02786af13c2da91969f5d56f056671bf91f208a5@190.2.146.45:26656,c0a9796aee8c283745852b2d406c4f40cc04b877@135.125.188.17:6095,82588f011491c6100d922d133f52fc23460b9231@135.181.172.181:26656,89757803f40da51678451735445ad40d5b15e059@169.155.169.156:26656,447faf8fc9f5376987c15e5f260fced9c34e3cdd@135.148.169.198:12956,de8dc02b7c1c1c3a28e9a428d1f8763f111df95f@198.244.179.127:26656,e726816f42831689eab9378d5d577f1d06d25716@176.9.188.21:26656,ea3fbfba42f063c4f00aa41ebb6e1161b63e09e8@15.235.114.194:10356,55aa7aac517b85bad6ee7fb41707029a331ccba0@15.235.66.89:10556,a8f339d59480908c9b1c420735ed15f577f218c5@185.119.118.112:3000,2bc2e7c2df7bd56edf4c88c237cf917504392c86@162.55.92.114:2050,d2247f7b919f0781c90ee61958d7044665a22d38@169.155.168.193:26656,7549de9e4fada385ec0bd2807f83f7d97c6a15ec@89.58.18.61:2000,7d312859acdc6af2d0798b5ea81204424c4ae0f5@162.19.89.8:10156,06cf62f1dda22ddb2fe1476f2ec24ef4c67bb1b6@176.31.182.146:12956,2c82317311aba7f42bfdfb7a0fb466f460721ea0@116.202.36.240:10356,d40a6fa0d2592ee3ac5d8ffa0ea2646ad76a18ce@188.165.230.75:12956,561eb93e3d8a09afd5cb3bb4ce988d4767ab1698@142.44.138.212:26656,02c25fcafd18ad31bd207e81eb25f39e053d0e90@65.108.193.42:27656,c382a9a0d4c0606d785d2c7c2673a0825f7c53b2@65.21.131.216:27756,89b576c3eb72a4f0c66dc0899bec7c21552ea2a5@23.88.7.73:29538,13d85b24a095ac1f1675fc7e1ae4bee8ed6cdfb9@154.53.58.111:26656,35c4ddfed043793d0c9fb8555cd1623fb46f5128@148.251.13.186:12956
  seeds: 77cbb35d1df17f48a42e9f157f12f55b691e9f5e@seeds.goldenratiostaking.net:1620,4936e377b4d4f17048f8961838a5035a4d21240c@chihuahua-seed-01.mercury-nodes.net:29540
  addrbook:
    enabled: true
    url: https://snapshots.polkachu.com/addrbook/chihuahua/addrbook.json

  # Pruning configuration
  pruning: "custom"
  pruning_keep_recent: "100"
  pruning_keep_every: "0"
  pruning_interval: "10"

  iavl_disable_fastnode: true

  proxy_app: "tcp://127.0.0.1:26658"
  fast_sync: true
  db_backend: "goleveldb"
  db_dir: "data"
  log_level: "info"
  log_format: "plain"
  genesis_file: "config/genesis.json"
  priv_validator_state_file: "data/priv_validator_state.json"
  priv_validator_key_file: "config/priv_validator_key.json"
  # priv_validator_key_file: ""
  # priv_validator_laddr: "tcp://127.0.0.1:26659"
  node_key_file: "config/node_key.json"
  abci: "socket"
  filter_peers: false
  rpc:
    laddr: "tcp://127.0.0.1:26657"
    cors_allowed_origins: "[]"
    cors_allowed_methods: "['HEAD', 'GET', 'POST']"
    cors_allowed_headers: "['Origin', 'Accept', 'Content-Type', 'X-Requested-With', 'X-Server-Time']"
    grpc_laddr: ""
    grpc_max_open_connections: 900
    unsafe: false
    max_open_connections: 900
    max_subscription_clients: 100
    max_subscriptions_per_client: 5
    experimental_subscription_buffer_size: 200
    experimental_websocket_write_buffer_size: 200
    experimental_close_on_slow_client: false
    timeout_broadcast_tx_commit: "10s"
    max_body_bytes: 1000000
    max_header_bytes: 1048576
    tls_cert_file: ""
    tls_key_file: ""
    pprof_laddr: "localhost:6060"
  p2p:
    laddr: "tcp://0.0.0.0:26656"
    external_address: ""
    upnp: false
    addr_book_file: "config/addrbook.json"
    addr_book_strict: true
    max_num_inbound_peers: 40
    max_num_outbound_peers: 10
    unconditional_peer_ids: ""
    persistent_peers_max_dial_period: "0s"
    flush_throttle_timeout: "100ms"
    max_packet_msg_payload_size: 1024
    send_rate: 5120000
    recv_rate: 5120000
    pex: true
    seed_mode: false
    private_peer_ids: ""
    allow_duplicate_ip: false
    handshake_timeout: "20s"
    dial_timeout: "3s"
  mempool:
    version: "v0"
    recheck: true
    broadcast: true
    wal_dir: ""
    size: 5000
    max_txs_bytes: 1073741824
    cache_size: 10000
    keep-invalid-txs-in-cache: false
    max_tx_bytes: 1048576
    max_batch_bytes: 0
    ttl-duration: "0s"
    ttl-num-blocks: 0
  statesync:
    enable: false
    rpc_servers: ""
    trust_height: 0
    trust_hash: ""
    trust_period: "168h0m0s"
    discovery_time: "15s"
    temp_dir: ""
    chunk_request_timeout: "10s"
    chunk_fetchers: "4"
  fastsync:
    version: "v0"
  consensus:
    wal_file: "data/cs.wal/wal"
    timeout_propose: "3s"
    timeout_propose_delta: "500ms"
    timeout_prevote: "1s"
    timeout_prevote_delta: "500ms"
    timeout_precommit: "1s"
    timeout_precommit_delta: "500ms"
    timeout_commit: "5s"
    double_sign_check_height: 0
    skip_timeout_commit: false
    create_empty_blocks: true
    create_empty_blocks_interval: "0s"
    peer_gossip_sleep_duration: "100ms"
    peer_query_maj23_sleep_duration: "2s"
  storage:
    discard_abci_responses: false
  tx_index:
    indexer: "kv"
    psql-conn: ""
  instrumentation:
    prometheus: true
    prometheus_listen_addr: ":26660"
    max_open_connections: 900
    namespace: "tendermint"

  halt_height: 0
  halt_time: 0
  min_retain_blocks: 0
  inter_block_cache: true
  index_events: "[]"
  iavl_cache_size: 781250

  telemetry:
    enabled: false
    serviceName: ""
    enableHostname: false
    enableHostnameLabel: false
    enableServiceLabel: false
    prometheusRetentionTime: 0
    globalLabels: "[]"

  api:
    enable: false
    swagger: false
    address: "tcp://0.0.0.0:1317"
    maxOpenConnections: 1000
    rpcReadTimeout: 10
    rpcWriteTimeout: 0
    rpcMaxBodyBytes: 1000000
    enabledUnsafeCors: false

  rosetta:
    enable: false
    address: ":8080"
    blockchain: "app"
    network: "network"
    retries: 3
    offline: false

  grpc:
    enable: true
    address: "0.0.0.0:9090"
  grpcWeb:
    enable: true
    address: "0.0.0.0:9091"
    enableUnsafeCors: false
  stateSync:
    snapshotInterval: 0
    snapshotKeepRecent: 2

  store:
    streamers: "[]"
  streamers:
    file:
      keys: "['*', ]"
      writeDir: ""
      prefix: ""
      outputMetadata: true
      stopNodeOnError: true
      fsync: false

# If your node gets connection troubles to Polkachu,
# make sure to get through the trouble-shooting section at
# https://www.polkachu.com/state_sync/chihuahua
state_sync:
  enabled: false
  rpc1: "https://chihuahua-rpc.polkachu.com:443"
  rpc2: "https://chihuahua-rpc.polkachu.com:443"
  node_id: "765ab0e15d4bcd7533b4bad8e596a1c42264a4fe@65.108.128.201:12956"
  # height_offset should equal the CHIHUAHUA_STATE_SYNC_SNAPSHOT_INTERVAL on the node which makes the state-sync snapshots
  height_offset: 2000

snapshots:
  enabled: false

microk8s:
  enabled: true
  hostpath: /data/chihuahua-validator

# Used for mounting CHIHUAHUA_HOME on a specific node
local_storage:
  enabled: false
  capacity: 100Gi
  path: /data/chihuahua-validator
  host: ""

# If the node is a validator
validator:
  enabled: true
  node_key: eyJwcml2X2tleSI6eyJ0eXBlIjoidGVuZGVybWludC9Qcml2S2V5RWQyNTUxOSIsInZhbHVlIjoieUhLSndQdTVRZ3AyMlpLTjAxMTNaMUhyVnZNSmo3RzdaMjNyd3RFZ0t1bUhvTjExZTQwUGdya2dHZEZqWk9JZmZISEQyVVAzcGhVRHQ4U2I0UEw5dkE9PSJ9fQo=
  priv_key: ewogICJhZGRyZXNzIjogIkY0MTlFNzY2QjY2QUU3NjU1OUQ1RTM5NTU4MjAwQzEyREY3ODNBMjciLAogICJwdWJfa2V5IjogewogICAgInR5cGUiOiAidGVuZGVybWludC9QdWJLZXlFZDI1NTE5IiwKICAgICJ2YWx1ZSI6ICJxb2FTNjNyNmpkTGVyV2hCeGNhcHZTYXZKUVljTjFYT09rNHBMYm0zMkZrPSIKICB9LAogICJwcml2X2tleSI6IHsKICAgICJ0eXBlIjogInRlbmRlcm1pbnQvUHJpdktleUVkMjU1MTkiLAogICAgInZhbHVlIjogIjJrVGtyMVlENDV5SCt4cTlodDlRZzNFL3UySUJ6WnZSdXdGdWsrellKcmVxaHBMcmV2cU4wdDZ0YUVIRnhxbTlKcThsQmh3M1ZjNDZUaWt0dWJmWVdRPT0iCiAgfQp9Cg==

# If the node is a fullnode (non-validator)
fullnode:
  enabled: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  domain: "dmain.tld"
