apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-stats.fullname" . }}
  labels:
    app: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.backendService.servicePort }}
      targetPort: {{ .Values.backendService.servicePort }}
      protocol: TCP
      name: backend
  selector:
    app: backend
