apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-stats.fullname" . }}
  labels:
    {{- include "backend-stats.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.backendService.servicePort }}
      targetPort: {{ .Values.backendService.servicePort }}
      protocol: TCP
      name: backend
  selector:
    {{- include "backend-stats.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-stats.fullname" . }}-redis
  labels:
    {{- include "backend-stats.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      protocol: TCP
      name: redis
  selector:
    {{- include "backend-stats.selectorLabels" . | nindent 4 }}