{{- if .Values.local_storage.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chihuahua-local-storage
spec:
  capacity:
    storage: {{ $.Values.local_storage.capacity }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: chihuahua-local-storage
  local:
    path: {{ $.Values.local_storage.path }}
  {{ if eq $.Values.microk8s.enabled false}}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ $.Values.local_storage.host }}
  {{ end }}
{{- end }}
