{{- if .Values.fullnode.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: chihuahua-fullnode
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 1317
      name: chihuahuad-api
    - port: 9090
      name: chihuahuad-grpc
    - port: 26660
      name: metrics
    - port: 26657
      name: chihuahuad-rpc
  selector:
    chihuahua.network/fullnode: "{{ .Values.chihuahua_node.moniker }}"
{{- end }}
{{- if .Values.archive.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: chihuahua-archive
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 1317
      name: chihuahuad-api
    - port: 9090
      name: chihuahuad-grpc
    - port: 26660
      name: metrics
    - port: 26657
      name: chihuahuad-rpc
  selector:
    chihuahua.network/archive: "{{ .Values.chihuahua_node.moniker }}"
{{- end }}
{{- if .Values.validator.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: chihuahua-validator
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 26656
      name: p2p
    - port: 26660
      name: metrics
    {{- if .Values.validator.tmkms }}
    - port: 26659
      name: kms
    {{- end }}
  selector:
    app: "chihuahua-validator"
{{- end }}
