---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  {{- if .Values.validator.enabled }}
  name: chihuahua-node-validator
  {{- else if .Values.fullnode.enabled }}
  name: chihuahua-node-fullnode
  {{- else if .Values.archive.enabled }}
  name: chihuahua-node-archive
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- if .Values.validator.enabled }}
    app: chihuahua-validator
    chihuahua.network/validator: "{{ .Values.chihuahua_node.moniker }}"
  {{- else if .Values.fullnode.enabled }}
    app: chihuahua-fullnode
    chihuahua.network/fullnode: "{{ .Values.chihuahua_node.moniker }}"
  {{- else if .Values.archive.enabled }}
    app: chihuahua-archive
    chihuahua.network/archive: "{{ .Values.chihuahua_node.moniker }}"
  {{- end }}
spec:
  replicas: 1
  {{- if .Values.validator.enabled }}
  serviceName: chihuahua-validator
  {{- else if .Values.fullnode.enabled }}
  serviceName: chihuahua-fullnode
  {{- else if .Values.archive.enabled }}
  serviceName: chihuahua-archive
  {{- end }}
  selector:
    matchLabels:
    {{- if .Values.validator.enabled }}
      app: chihuahua-validator
      chihuahua.network/validator: "{{ .Values.chihuahua_node.moniker }}"
    {{- else if .Values.fullnode.enabled }}
      app: chihuahua-fullnode
      chihuahua.network/fullnode: "{{ .Values.chihuahua_node.moniker }}"
    {{- else if .Values.archive.enabled }}
      app: chihuahua-archive
      chihuahua.network/archive: "{{ .Values.chihuahua_node.moniker }}"
    {{- end }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
      {{- if .Values.validator.enabled }}
        app: chihuahua-validator
        chihuahua.network/validator: "{{ .Values.chihuahua_node.moniker }}"
      {{- else if .Values.fullnode.enabled }}
        app: chihuahua-fullnode
        chihuahua.network/fullnode: "{{ .Values.chihuahua_node.moniker }}"
      {{- else if .Values.archive.enabled }}
        app: chihuahua-archive
        chihuahua.network/archive: "{{ .Values.chihuahua_node.moniker }}"
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- if .Values.validator.enabled }}
      serviceAccountName: chihuahua-validator
    {{- else if .Values.fullnode.enabled }}
      ServiceAccountName: chihuahua-fullnode
    {{- else if .Values.archive.enabled }}
      ServiceAccountName: chihuahua-archive
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.local_storage.enabled }}
      nodeSelector:
        kubernetes.io/hostname: {{ $.Values.local_storage.host }}
      {{- end }}
      initContainers:
        - name: init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: [ "/bin/bash" , "/config/init.sh" ]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CHIHUAHUA_MONIKER
              value: {{ .Values.chihuahua_node.moniker }}
            - name: CHIHUAHUA_NET
              value: {{ .Values.chihuahua_node.net }}
            - name: CHIHUAHUA_HOME
              value: {{ .Values.home }}
            - name: CHIHUAHUA_CHAIN_ID
              value: {{ .Values.chihuahua_node.chainid }}
            - name: CHIHUAHUA_KEYRING_BACKEND
              value: {{ .Values.keyring_backend }}
            - name: CHIHUAHUA_ADDRBOOK_ENABLED
              value: "{{ .Values.chihuahua_node.addrbook.enabled }}"
            - name: CHIHUAHUA_ADDRBOOK_URL
              value: {{ .Values.chihuahua_node.addrbook.url }}
            {{- if .Values.state_sync.enabled }}
            - name: CHIHUAHUA_P2P_PERSISTENT_PEERS
              value: {{ .Values.chihuahua_node.peers }},{{ .Values.state_sync.node_id }}
            {{- else if not .Values.chihuahua_node.addrbook.enabled }}
            - name: CHIHUAHUA_P2P_PERSISTENT_PEERS
              value: {{ .Values.chihuahua_node.peers }}
            {{- end }}
            - name: CHIHUAHUA_IAVL_DISABLE_FASTNODE
              value: "{{ .Values.chihuahua_node.iavl_disable_fastnode }}"
            - name: CHIHUAHUA_DEBUG
              value: "{{ $.Values.debug }}"
            - name: CHIHUAHUA_MINIMUM_GAS_PRICES
              value: "{{ .Values.chihuahua_node.minimum_gas_prices }}"
            - name: SNAPSHOT_PROVIDER
              value: "{{ .Values.chihuahua_node.snapshot_provider }}"
            {{- if .Values.state_sync.enabled }}
            - name: CHIHUAHUA_STATESYNC_ENABLE
              value: "true"
            - name: CHIHUAHUA_STATESYNC_RPC_SERVERS
              value: "{{ .Values.state_sync.rpc1 }},{{ .Values.state_sync.rpc2 }}"
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            {{- if .Values.validator.enabled }}
            - name: chihuahua-validator-config-toml
            {{ else if .Values.fullnode.enabled }}
            - name: chihuahua-fullnode-config-toml
            {{- else if .Values.archive.enabled }}
            - name: chihuahua-archive-config-toml
            {{- end }}
              mountPath: {{ .Values.home }}/config/config.toml
              subPath: config.toml
            {{- if .Values.validator.enabled }}
            - name: chihuahua-validator-app-toml
            {{- else if .Values.fullnode.enabled }}
            - name: chihuahua-fullnode-app-toml
            {{- else if .Values.archive.enabled }}
            - name: chihuahua-archive-app-toml
            {{- end }}
              mountPath: {{ .Values.home }}/config/app.toml
              subPath: app.toml
          {{- if .Values.local_storage.enabled }}
            - name: local-persistent-storage
              mountPath: "{{ .Values.home }}"
          {{- else }}
            - name: home
              mountPath: "{{ .Values.home }}"
          {{- end }}
          {{- if .Values.validator.enabled }}
            - name: node-key
              mountPath: /root/.chihuahuad/config/node_key.json
            - name: priv-validator-key
              mountPath: /root/.chihuahuad/config/priv_validator_key.json
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: [ "/bin/chihuahuad" , "start" ]
          {{- if .Values.archive.enabled }}
          args: ["--pruning={{ .Values.chihuahua_node.pruning }}"]
          {{- else }}
          args: ["--pruning={{ .Values.chihuahua_node.pruning }}",
                "--pruning-interval={{ .Values.chihuahua_node.pruning_interval }}",
                "--pruning-keep-recent={{ .Values.chihuahua_node.pruning_keep_recent }}"]
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CHIHUAHUA_MONIKER
              value: {{ .Values.chihuahua_node.moniker }}
            - name: CHIHUAHUA_NET
              value: {{ .Values.chihuahua_node.net }}
            - name: CHIHUAHUA_HOME
              value: {{ .Values.home }}
            - name: CHIHUAHUA_CHAIN_ID
              value: {{ .Values.chihuahua_node.chainid }}
            - name: CHIHUAHUA_KEYRING_BACKEND
              value: {{ .Values.keyring_backend }}
            {{- if .Values.state_sync.enabled }}
            - name: CHIHUAHUA_P2P_PERSISTENT_PEERS
              value: {{ .Values.chihuahua_node.peers }},{{ .Values.state_sync.node_id }}
            {{- else if not .Values.chihuahua_node.addrbook.enabled }}
            - name: CHIHUAHUA_P2P_PERSISTENT_PEERS
              value: {{ .Values.chihuahua_node.peers }}
            {{- end }}
            {{- if .Values.snapshots.enabled }}
            - name: CHIHUAHUA_STATE_SYNC_SNAPSHOT_INTERVAL
              value: "2000"
            - name: CHIHUAHUA_STATE_SYNC_SNAPSHOT_KEEP_RECENT
              value: "5"
            - name: CHIHUAHUA_PRUNING
              value: "custom"
            - name: CHIHUAHUA_PRUNING_KEEP_RECENT
              value: "100"
            - name: CHIHUAHUA_PRUNING_KEEP_EVERY
              value: "2000"
            - name: CHIHUAHUA_PRUNING_INTERVAL
              value: "10"
            {{- else }}
            - name: CHIHUAHUA_PRUNING
              value: "{{ .Values.chihuahua_node.pruning }}"
            - name: CHIHUAHUA_PRUNING_KEEP_RECENT
              value: "{{ .Values.chihuahua_node.pruning_keep_recent }}"
            - name: CHIHUAHUA_PRUNING_KEEP_EVERY
              value: "{{ .Values.chihuahua_node.pruning_keep_every }}"
            - name: CHIHUAHUA_PRUNING_INTERVAL
              value: "{{ .Values.chihuahua_node.pruning_interval }}"
            {{- end }}
            - name: CHIHUAHUA_IAVL_DISABLE_FASTNODE
              value: "{{ .Values.chihuahua_node.iavl_disable_fastnode }}"
            - name: CHIHUAHUA_P2P_LADDR
              value: tcp://0.0.0.0:26656
            - name: CHIHUAHUA_RPC_LADDR
              value: tcp://0.0.0.0:26657
            - name: CHIHUAHUA_RPC_PPROF_LADDR
              value: 0.0.0.0:6060
            - name: CHIHUAHUA_GRPC_ADDRESS
              value: 0.0.0.0:9090
            - name: CHIHUAHUA_P2P_ADDR_BOOK_STRICT
              value: "false"
            - name: CHIHUAHUA_ROSETTA_ENABLE
              value: "false"
            - name: CHIHUAHUA_P2P_SEED_MODE
              value: "true"
            - name: CHIHUAHUA_P2P_PEX
              value: "{{ .Values.chihuahua_node.p2p.pex }}"
            - name: CHIHUAHUA_DEBUG
              value: "{{ $.Values.debug }}"
            - name: CHIHUAHUA_MINIMUM_GAS_PRICES
              value: "{{ .Values.chihuahua_node.minimum_gas_prices }}"
            - name: SNAPSHOT_PROVIDER
              value: "{{ .Values.chihuahua_node.snapshot_provider }}"
            {{- if .Values.state_sync.enabled }}
            - name: CHIHUAHUA_STATESYNC_ENABLE
              value: "true"
            - name: CHIHUAHUA_STATESYNC_RPC_SERVERS
              value: "{{ .Values.state_sync.rpc1 }},{{ .Values.state_sync.rpc2 }}"
            {{- end }}
            - name: CHIHUAHUA_API_ENABLE
              value: "{{ .Values.chihuahua_node.api_enable }}"
          ports:
            - containerPort: 26660
              name: metrics
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            {{- if .Values.validator.enabled }}
            - name: chihuahua-validator-config-toml
            {{- else if .Values.fullnode.enabled }}
            - name: chihuahua-fullnode-config-toml
            {{- else if .Values.archive.enabled }}
            - name: chihuahua-archive-config-toml
            {{- end }}
              mountPath: {{ .Values.home }}/config/config.toml
              subPath: config.toml
            {{- if .Values.validator.enabled }}
            - name: chihuahua-validator-app-toml
            {{- else if .Values.fullnode.enabled }}
            - name: chihuahua-fullnode-app-toml
            {{- else if .Values.archive.enabled }}
            - name: chihuahua-archive-app-toml
            {{- end }}
              mountPath: {{ .Values.home }}/config/app.toml
              subPath: app.toml
          {{- if .Values.local_storage.enabled }}
            - name: local-persistent-storage
              mountPath: "{{ .Values.home }}"
          {{- else }}
            - name: home
              mountPath: "{{ .Values.home }}"
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: chihuahua-node-config
        {{- if .Values.validator.enabled }}
        - name: chihuahua-validator-config-toml
          configMap:
            name: chihuahua-validator-config-toml
        - name: chihuahua-validator-app-toml
          configMap:
            name: chihuahua-validator-app-toml
        {{- else if .Values.fullnode.enabled }}
        - name: chihuahua-fullnode-config-toml
          configMap:
            name: chihuahua-fullnode-config-toml
        - name: chihuahua-fullnode-app-toml
          configMap:
            name: chihuahua-fullnode-app-toml
        {{- else if .Values.archive.enabled }}
        - name: chihuahua-archive-config-toml
          configMap:
            name: chihuahua-archive-config-toml
        - name: chihuahua-archive-app-toml
          configMap:
            name: chihuahua-archive-app-toml
        {{- end }}
      {{- if .Values.microk8s.enabled }}
        - name: home
          hostPath:
            # Ensure the file directory is created.
            path: "{{ .Values.microk8s.hostpath }}"
            type: DirectoryOrCreate
      {{- end }}
      {{- if .Values.validator.enabled }}
        - name: priv-validator-key
          secret:
            secretName: priv-validator-key
        - name: node-key
          secret:
            secretName: node-key
      {{- end }}
