# Default values for crescent-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "ghcr.io/fix-me"
  tag: "crescent-v4.2.0"
  pullPolicy: IfNotPresent

# Common Values

keyring_backend: "test"
home: "/root/.crescent"
debug: "false"

# Set Values to run a single crescent node connected to an existing network
# Defaults to mainnet
crescent_node:
  # snapshot_provider can be either "polkachu" (2Gi), "autostake" (1Gi). Otherwise it'll default to a much larger in size.
  snapshot_provider: "polkachu"
  api_enable: "false"
  moniker: yourminikerhere
  chainid: crescent-1
  # disable PEX when nodes have issues with syncing / catching up / peer dial errors/flood
  minimum_gas_prices: 0.02ucre
  net: https://snapshots.polkachu.com/genesis/crescent/genesis.json
  peers: 86030850dd635cab1f136979568087407a025491@46.101.153.158:26656,cab5e74240796743fd5c03c06daaf94b80062d50@185.16.38.210:26816,0da1931b5df7689cf2d9a5ccacc37c764a72c205@95.214.53.233:26816,dd16ce3d363dc4eb703c611f754faef335640d5c@38.242.200.146:26656,2e2ef0a6b5166d54cbfd976ad1ad30c1108b9dd9@65.108.142.81:26667,a8fea8a59a24b09c1b2e3c130cb97aa3cd041677@78.47.100.211:26656,929f22a7b04ff438da9edcfebd8089908239de44@13.115.84.112:26656,480c9cc2b9b701cf8a197e5d89bcd68a2bfd2369@34.85.96.42:26656,27f9d1074be7798e7bd9ed814bb673808e3adf97@148.251.51.154:26656,6607ace4e3e446c5ed3e03850eb9d99ad68db1bd@185.119.118.111:3000,68787e8412ab97d99af7595c46514b9ab4b3df45@54.199.211.124:26656,a7a817c3f548b78736c78f1dcd5b2ee131fbd887@185.248.24.28:26656,b5c3d9cef5e0e6b55342237c3026b89817029a96@65.109.90.96:46656,479234fc99b271c9e948f30bb9785550c1db7668@93.159.130.3:26656,359e6d62228c145b71b20ee2d901717e3a270655@198.244.229.43:26656,17aa8beb8548832af86abda7a83fe4a0a6ba46dd@217.160.246.151:26656,7147612c8c3ad51e80e6ab6f64a11717804edfe7@65.108.232.104:14556,1bdadb5876d3a34379a3e243b1bb5f2191aa342d@66.45.251.38:56656,a3767f3a4b0dffd4ebc860a3f41c351111d779db@206.189.87.11:26656,d85a3bb3ea9522c34b5afc1f4dbd537112a7bde8@5.9.99.172:14556,bb2a2b742ba69cdf7ad635778d6f7784b264b6b6@54.95.40.202:26656,23751903ed3ee22808abe56c4a90eaeb6efa2f63@162.55.245.149:2120,d73da4c900563b834c0eb612a6ab679471d250bc@51.75.146.179:4050,3b60a29d89cd7ef6a8d0c7ba32013d7f2051e082@135.181.113.227:1406,f373e6a868ee7e67060bc49efec58cd9b82ac764@54.178.136.194:26656,291d178f780f495b0c0baca0a7a22123e0cac7e8@65.108.234.105:3000,08379b23453595f34271381cdb299c4157fbc1a0@51.250.105.195:26656,cd73ec44403a024f5bf05dc0c7d0289dbbc469a6@65.21.229.33:25656,c669bf70119df120d850c2141db21c5ec0e3f9fb@148.251.246.239:28007,43a14300d254ee7ae533f3bde3e42c44a651a333@149.202.87.117:16656,cbca2e1a3bbfa734ba23c15f5a1a74b2bc4f1e79@193.70.45.106:14556,c26aad500bcd1d75efc643b185fdf50e8abe5c19@149.202.65.148:16656,9288b8bebc968b1e39e75f487350681aaaf7809b@93.189.30.122:26656,cf77bc886bfe40acc8d06327b41430c9822de89f@195.14.6.2:26656,7bd68e3acc1a52ef9d88904bbb3a3bf7ac3e157d@15.235.50.175:26661,e62d4deb52b8a56809c7d8e389ffe1dbe604de18@167.86.91.77:26656,584646cddd9de17340f78668170c22c4eb288a7e@172.104.109.177:26656,e3bec7aba63bd30dd2c1fe54bfd021ac30303144@49.13.16.92:27002,c82327eec36e457594ce88da7e5d03a5c48aabc7@65.109.32.148:26736,e6fd1c72c0784362a837bcb836debb41c31d2502@5.78.101.137:26656,589f90c2f0e9790450b3922c62dda8760e23301c@52.52.52.118:26656,b7447a5ded7f41d94dcec58f845f85005be4415d@65.21.122.47:30656,4c03d91612825e0ad9b5fe59e770148b0e91f236@65.108.237.88:27000,12dffd084db659d364a7d99bf95a5979e2fc2c62@18.178.97.230:26656,6672a23598228b7e8e4cb951631d138edd9e041d@173.212.251.133:26756,ebc272824924ea1a27ea3183dd0b9ba713494f83@185.16.39.158:26816,3b0228a38ca650eec186c4ff855f6cfd8b6ddd3e@148.251.13.186:14556,2277e8d7a7d21f7cfebd1d8dcfa222afb7abcb99@103.180.28.212:26656,50eef540fff0d2dac438b3eab2ad30d9939076ae@176.126.87.56:26656
  seeds:
  addrbook:
    enabled: true
    url: https://snapshots.polkachu.com/addrbook/crescent/addrbook.json

  # Pruning configuration
  pruning: "custom"
  pruning_keep_recent: "100"
  pruning_keep_every: "0"
  pruning_interval: "10"

  iavl_disable_fastnode: true

  proxy_app: "tcp://127.0.0.1:26658"
  fast_sync: true
  db_backend: "goleveldb"
  db_dir: "data"
  log_level: "info"
  log_format: "plain"
  genesis_file: "config/genesis.json"
  priv_validator_state_file: "data/priv_validator_state.json"
  priv_validator_key_file: "config/priv_validator_key.json"
  # priv_validator_key_file: ""
  # priv_validator_laddr: "tcp://127.0.0.1:26659"
  node_key_file: "config/node_key.json"
  abci: "socket"
  filter_peers: false
  rpc:
    laddr: "tcp://127.0.0.1:26657"
    cors_allowed_origins: "[]"
    cors_allowed_methods: "['HEAD', 'GET', 'POST']"
    cors_allowed_headers: "['Origin', 'Accept', 'Content-Type', 'X-Requested-With', 'X-Server-Time']"
    grpc_laddr: ""
    grpc_max_open_connections: 900
    unsafe: false
    max_open_connections: 900
    max_subscription_clients: 100
    max_subscriptions_per_client: 5
    experimental_subscription_buffer_size: 200
    experimental_websocket_write_buffer_size: 200
    experimental_close_on_slow_client: false
    timeout_broadcast_tx_commit: "10s"
    max_body_bytes: 1000000
    max_header_bytes: 1048576
    tls_cert_file: ""
    tls_key_file: ""
    pprof_laddr: "localhost:6060"
  p2p:
    laddr: "tcp://0.0.0.0:26656"
    external_address: ""
    upnp: false
    addr_book_file: "config/addrbook.json"
    addr_book_strict: true
    max_num_inbound_peers: 40
    max_num_outbound_peers: 10
    unconditional_peer_ids: ""
    persistent_peers_max_dial_period: "0s"
    flush_throttle_timeout: "100ms"
    max_packet_msg_payload_size: 1024
    send_rate: 5120000
    recv_rate: 5120000
    pex: true
    seed_mode: false
    private_peer_ids: ""
    allow_duplicate_ip: false
    handshake_timeout: "20s"
    dial_timeout: "3s"
  mempool:
    version: "v0"
    recheck: true
    broadcast: true
    wal_dir: ""
    size: 5000
    max_txs_bytes: 1073741824
    cache_size: 10000
    keep-invalid-txs-in-cache: false
    max_tx_bytes: 1048576
    max_batch_bytes: 0
    ttl-duration: "0s"
    ttl-num-blocks: 0
  statesync:
    enable: false
    rpc_servers: ""
    trust_height: 0
    trust_hash: ""
    trust_period: "168h0m0s"
    discovery_time: "15s"
    temp_dir: ""
    chunk_request_timeout: "10s"
    chunk_fetchers: "4"
  fastsync:
    version: "v0"
  consensus:
    wal_file: "data/cs.wal/wal"
    timeout_propose: "3s"
    timeout_propose_delta: "500ms"
    timeout_prevote: "1s"
    timeout_prevote_delta: "500ms"
    timeout_precommit: "1s"
    timeout_precommit_delta: "500ms"
    timeout_commit: "5s"
    double_sign_check_height: 0
    skip_timeout_commit: false
    create_empty_blocks: true
    create_empty_blocks_interval: "0s"
    peer_gossip_sleep_duration: "100ms"
    peer_query_maj23_sleep_duration: "2s"
  storage:
    discard_abci_responses: false
  tx_index:
    indexer: "kv"
    psql-conn: ""
  instrumentation:
    prometheus: true
    prometheus_listen_addr: ":26660"
    max_open_connections: 900
    namespace: "tendermint"

  halt_height: 0
  halt_time: 0
  min_retain_blocks: 0
  inter_block_cache: true
  index_events: "[]"
  iavl_cache_size: 781250

  telemetry:
    enabled: false
    serviceName: ""
    enableHostname: false
    enableHostnameLabel: false
    enableServiceLabel: false
    prometheusRetentionTime: 0
    globalLabels: "[]"

  api:
    enable: false
    swagger: false
    address: "tcp://0.0.0.0:1317"
    maxOpenConnections: 1000
    rpcReadTimeout: 10
    rpcWriteTimeout: 0
    rpcMaxBodyBytes: 1000000
    enabledUnsafeCors: false

  rosetta:
    enable: false
    address: ":8080"
    blockchain: "app"
    network: "network"
    retries: 3
    offline: false

  grpc:
    enable: true
    address: "0.0.0.0:9090"
  grpcWeb:
    enable: true
    address: "0.0.0.0:9091"
    enableUnsafeCors: false
  stateSync:
    snapshotInterval: 0
    snapshotKeepRecent: 2

state_sync:
  enabled: false
  rpc1: "https://crescent-rpc.polkachu.com:443"
  node_id: ""
  # height_offset should equal the CRESCENT_STATE_SYNC_SNAPSHOT_INTERVAL on the node which makes the state-sync snapshots
  height_offset: 2000

snapshots:
  enabled: false

microk8s:
  enabled: true
  hostpath: /data/crescent-validator

# Used for mounting CRESCENT_HOME on a specific node
local_storage:
  enabled: false
  capacity: 100Gi
  path: /data/crescent-validator
  host: ""

# If the node is a validator
validator:
  enabled: true
  node_key: ""
  priv_key: ""
  tmkms: false
  
# If the node is a fullnode (non-validator)
fullnode:
  enabled: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  domain: "dmain.tld"
