{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tenderduty.fullname" . }}
  labels:
    {{- include "tenderduty.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: tenderduty
                port:
                  number: {{ .Values.listen_port }}
{{- end }}