{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mayanode.serviceAccountName" . }}
  labels:
{{ include "mayanode.labels" . | nindent 4 }}
{{- end -}}
