# Default values for bitcanna-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "ghcr.io/akash-network/cosmos-omnibus"
  tag: "v0.3.36-bitcanna-v1.7.0"
  pullPolicy: IfNotPresent

# Common Values

keyring_backend: "test"
home: "/root/.bcna"
debug: "false"

# Set Values to run a single bitcanna node connected to an existing network
# Defaults to mainnet
bitcanna_node:
  # snapshot_provider can be either "polkachu" (2Gi), "autostake" (1Gi). Otherwise it'll default to a much larger in size.
  snapshot_provider: "polkachu"
  api_enable: "false"
  moniker: yourminikerhere
  chainid: bitcanna-1
  # disable PEX when nodes have issues with syncing / catching up / peer dial errors/flood
  minimum_gas_prices: 0.025ubcna
  net: https://raw.githubusercontent.com/BitCannaGlobal/bcna/main/genesis.json
  peers: a7d96dc929824613315dcc1c90fee119f28cc51f@134.65.193.132:26656,c6658742ae4c889ecf8dee95ca2a8e4b45d46dfd@85.214.208.127:26656,26371443a1c2576c3815cb49e84ec436b457c276@24.158.14.210:26656,5cfb82bd566ad3c5330c8326f0da5c7f048aca25@81.0.218.135:24356,88c6b1fa1c7fef98b4449b769eb2705476586664@65.109.92.241:21326,23671067d0fd40aec523290585c7d8e91034a771@65.108.43.170:26656,ce53943e31e15bf12549084e1aabc78f6908e342@57.128.75.17:26050,104d7ec9d84c8da66b97d50669b8ba58f1b60470@62.171.180.31:26656,89757803f40da51678451735445ad40d5b15e059@169.155.168.66:26656,cb0848b84987c37ba0fa465585c6b9d6cec6deab@65.108.77.98:26696,07c829cf936db34be61143fabb09541d05aea899@65.108.98.124:64206,f68feb1847416930fa046a303242adde39ba92e6@154.12.232.8:26656,d8a0facda705edbbdd2d79fb302e017df009e9da@207.244.231.189:26656
  seeds: 
  addrbook:
    enabled: true
    url: https://snapshots.polkachu.com/addrbook/bitcanna/addrbook.json

  # Pruning configuration
  pruning: "custom"
  pruning_keep_recent: "100"
  pruning_keep_every: "0"
  pruning_interval: "10"

  iavl_disable_fastnode: true

  proxy_app: "tcp://127.0.0.1:26658"
  fast_sync: true
  db_backend: "goleveldb"
  db_dir: "data"
  log_level: "info"
  log_format: "plain"
  genesis_file: "config/genesis.json"
  priv_validator_state_file: "data/priv_validator_state.json"
  priv_validator_key_file: "config/priv_validator_key.json"
  # priv_validator_key_file: ""
  # priv_validator_laddr: "tcp://127.0.0.1:26659"
  node_key_file: "config/node_key.json"
  abci: "socket"
  filter_peers: false
  rpc:
    laddr: "tcp://127.0.0.1:26657"
    cors_allowed_origins: "[]"
    cors_allowed_methods: "['HEAD', 'GET', 'POST']"
    cors_allowed_headers: "['Origin', 'Accept', 'Content-Type', 'X-Requested-With', 'X-Server-Time']"
    grpc_laddr: ""
    grpc_max_open_connections: 900
    unsafe: false
    max_open_connections: 900
    max_subscription_clients: 100
    max_subscriptions_per_client: 5
    experimental_subscription_buffer_size: 200
    experimental_websocket_write_buffer_size: 200
    experimental_close_on_slow_client: false
    timeout_broadcast_tx_commit: "10s"
    max_body_bytes: 1000000
    max_header_bytes: 1048576
    tls_cert_file: ""
    tls_key_file: ""
    pprof_laddr: "localhost:6060"
  p2p:
    laddr: "tcp://0.0.0.0:26656"
    external_address: ""
    upnp: false
    addr_book_file: "config/addrbook.json"
    addr_book_strict: true
    max_num_inbound_peers: 40
    max_num_outbound_peers: 10
    unconditional_peer_ids: ""
    persistent_peers_max_dial_period: "0s"
    flush_throttle_timeout: "100ms"
    max_packet_msg_payload_size: 1024
    send_rate: 5120000
    recv_rate: 5120000
    pex: true
    seed_mode: false
    private_peer_ids: ""
    allow_duplicate_ip: false
    handshake_timeout: "20s"
    dial_timeout: "3s"
  mempool:
    version: "v0"
    recheck: true
    broadcast: true
    wal_dir: ""
    size: 5000
    max_txs_bytes: 1073741824
    cache_size: 10000
    keep-invalid-txs-in-cache: false
    max_tx_bytes: 1048576
    max_batch_bytes: 0
    ttl-duration: "0s"
    ttl-num-blocks: 0
  statesync:
    enable: false
    rpc_servers: ""
    trust_height: 0
    trust_hash: ""
    trust_period: "168h0m0s"
    discovery_time: "15s"
    temp_dir: ""
    chunk_request_timeout: "10s"
    chunk_fetchers: "4"
  fastsync:
    version: "v0"
  consensus:
    wal_file: "data/cs.wal/wal"
    timeout_propose: "3s"
    timeout_propose_delta: "500ms"
    timeout_prevote: "1s"
    timeout_prevote_delta: "500ms"
    timeout_precommit: "1s"
    timeout_precommit_delta: "500ms"
    timeout_commit: "5s"
    double_sign_check_height: 0
    skip_timeout_commit: false
    create_empty_blocks: true
    create_empty_blocks_interval: "0s"
    peer_gossip_sleep_duration: "100ms"
    peer_query_maj23_sleep_duration: "2s"
  storage:
    discard_abci_responses: false
  tx_index:
    indexer: "kv"
    psql-conn: ""
  instrumentation:
    prometheus: true
    prometheus_listen_addr: ":26660"
    max_open_connections: 900
    namespace: "tendermint"

  halt_height: 0
  halt_time: 0
  min_retain_blocks: 0
  inter_block_cache: true
  index_events: "[]"
  iavl_cache_size: 781250

  telemetry:
    enabled: false
    serviceName: ""
    enableHostname: false
    enableHostnameLabel: false
    enableServiceLabel: false
    prometheusRetentionTime: 0
    globalLabels: "[]"

  api:
    enable: false
    swagger: false
    address: "tcp://0.0.0.0:1317"
    maxOpenConnections: 1000
    rpcReadTimeout: 10
    rpcWriteTimeout: 0
    rpcMaxBodyBytes: 1000000
    enabledUnsafeCors: false

  rosetta:
    enable: false
    address: ":8080"
    blockchain: "app"
    network: "network"
    retries: 3
    offline: false

  grpc:
    enable: true
    address: "0.0.0.0:9090"
  grpcWeb:
    enable: true
    address: "0.0.0.0:9091"
    enableUnsafeCors: false
  stateSync:
    snapshotInterval: 0
    snapshotKeepRecent: 2

  store:
    streamers: "[]"
  streamers:
    file:
      keys: "['*', ]"
      writeDir: ""
      prefix: ""
      outputMetadata: true
      stopNodeOnError: true
      fsync: false

# If your node gets connection troubles to Polkachu,
# make sure to get through the trouble-shooting section at
# https://polkachu.com/state_sync/bitcanna
state_sync:
  enabled: false
  rpc1: "https://bitcanna-rpc.polkachu.com:443"
  rpc2: "https://bitcanna-rpc.polkachu.com:443"
  node_id: ""
  # height_offset should equal the BITCANNA_STATE_SYNC_SNAPSHOT_INTERVAL on the node which makes the state-sync snapshots
  height_offset: 2000

snapshots:
  enabled: false

microk8s:
  enabled: true
  hostpath: /data/bitcanna-validator

# Used for mounting BITCANNA_HOME on a specific node
local_storage:
  enabled: false
  capacity: 100Gi
  path: /data/bitcanna-validator
  host: ""

# If the node is a validator
validator:
  enabled: true
  node_key: ""
  priv_key: ""
  
# If the node is a fullnode (non-validator)
fullnode:
  enabled: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  domain: "dmain.tld"
