apiVersion: v1
kind: Service
metadata:
  name: peggo-exporter
  labels:
    app: peggo-exporter
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.servicePort }}
      protocol: TCP
      name: peggo-exporter
  selector:
    app: peggo-exporter
