---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  {{- if .Values.validator.enabled }}
  name: cosmoshub-node-validator
  {{- else }}
  name: cosmoshub-node-fullnode
  {{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- if .Values.validator.enabled }}
    app: cosmoshub-validator
    cosmoshub.network/validator: "{{ .Values.cosmoshub_node.moniker }}"
  {{- else }}
    app: cosmoshub-fullnode
    cosmoshub.network/fullnode: "{{ .Values.cosmoshub_node.moniker }}"
  {{- end }}
spec:
  replicas: 1
  {{- if .Values.validator.enabled }}
  serviceName: cosmoshub-validator
  {{- else }}
  serviceName: cosmoshub-fullnode
  {{- end }}
  selector:
    matchLabels:
    {{- if .Values.validator.enabled }}
      app: cosmoshub-validator
      cosmoshub.network/validator: "{{ .Values.cosmoshub_node.moniker }}"
    {{- else }}
      app: cosmoshub-fullnode
      cosmoshub.network/fullnode: "{{ .Values.cosmoshub_node.moniker }}"
    {{- end }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
      {{- if .Values.validator.enabled }}
        app: cosmoshub-validator
        cosmoshub.network/validator: "{{ .Values.cosmoshub_node.moniker }}"
      {{- else }}
        app: cosmoshub-fullnode
        cosmoshub.network/fullnode: "{{ .Values.cosmoshub_node.moniker }}"
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- if .Values.validator.enabled }}
      serviceAccountName: cosmoshub-validator
    {{- else }}
      ServiceAccountName: cosmoshub-fullnode
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.local_storage.enabled }}
      nodeSelector:
        kubernetes.io/hostname: {{ $.Values.local_storage.host }}
      {{- end }}
      initContainers:
        - name: init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: [ "/bin/bash" , "/config/init.sh" ]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: COSMOSHUB_MONIKER
              value: {{ .Values.cosmoshub_node.moniker }}
            - name: COSMOSHUB_NET
              value: {{ .Values.cosmoshub_node.net }}
            - name: COSMOSHUB_HOME
              value: {{ .Values.home }}
            - name: COSMOSHUB_CHAIN_ID
              value: {{ .Values.cosmoshub_node.chainid }}
            - name: COSMOSHUB_KEYRING_BACKEND
              value: {{ .Values.keyring_backend }}
            - name: COSMOSHUB_ADDRBOOK_ENABLED
              value: "{{ .Values.cosmoshub_node.addrbook.enabled }}"
            - name: COSMOSHUB_ADDRBOOK_URL
              value: {{ .Values.cosmoshub_node.addrbook.url }}
            {{- if .Values.state_sync.enabled }}
            - name: COSMOSHUB_P2P_PERSISTENT_PEERS
              value: {{ .Values.cosmoshub_node.peers }},{{ .Values.state_sync.node_id }}
            {{- else if not .Values.cosmoshub_node.addrbook.enabled }}
            - name: COSMOSHUB_P2P_PERSISTENT_PEERS
              value: {{ .Values.cosmoshub_node.peers }}
            {{- end }}
            - name: COSMOSHUB_IAVL_DISABLE_FASTNODE
              value: "{{ .Values.cosmoshub_node.iavl_disable_fastnode }}"
            - name: COSMOSHUB_DEBUG
              value: "{{ $.Values.debug }}"
            - name: COSMOSHUB_MINIMUM_GAS_PRICES
              value: "{{ .Values.cosmoshub_node.minimum_gas_prices }}"
            - name: SNAPSHOT_PROVIDER
              value: "{{ .Values.cosmoshub_node.snapshot_provider }}"
            {{- if .Values.state_sync.enabled }}
            - name: COSMOSHUB_STATESYNC_ENABLE
              value: "true"
            - name: COSMOSHUB_STATESYNC_RPC_SERVERS
              value: "{{ .Values.state_sync.rpc1 }},{{ .Values.state_sync.rpc2 }}"
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            {{- if .Values.validator.enabled }}
            - name: cosmoshub-validator-config-toml
            {{- else }}
            - name: cosmoshub-fullnode-config-toml
            {{- end }}
              mountPath: {{ .Values.home }}/config/config.toml
              subPath: config.toml
            {{- if .Values.validator.enabled }}
            - name: cosmoshub-validator-app-toml
            {{- else }}
            - name: cosmoshub-fullnode-app-toml
            {{- end }}
              mountPath: {{ .Values.home }}/config/app.toml
              subPath: app.toml
          {{- if .Values.local_storage.enabled }}
            - name: local-persistent-storage
              mountPath: "{{ .Values.home }}"
          {{- else }}
            - name: home
              mountPath: "{{ .Values.home }}"
          {{- end }}
          {{- if .Values.validator.enabled }}
            - name: node-key
              mountPath: {{ .Values.home }}/config/node_key.json
              subPath: node_key.json
            - name: priv-validator-key
              mountPath: {{ .Values.home }}/config/priv_validator_key.json
              subPath: priv_validator_key.json
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: [ "/bin/gaiad" , "start" ]
          args: ["--pruning={{ .Values.cosmoshub_node.pruning }}",
                "--pruning-interval={{ .Values.cosmoshub_node.pruning_interval }}",
                "--pruning-keep-recent={{ .Values.cosmoshub_node.pruning_keep_recent }}"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: COSMOSHUB_MONIKER
              value: {{ .Values.cosmoshub_node.moniker }}
            - name: COSMOSHUB_NET
              value: {{ .Values.cosmoshub_node.net }}
            - name: COSMOSHUB_HOME
              value: {{ .Values.home }}
            - name: COSMOSHUB_CHAIN_ID
              value: {{ .Values.cosmoshub_node.chainid }}
            - name: COSMOSHUB_KEYRING_BACKEND
              value: {{ .Values.keyring_backend }}
            {{- if .Values.state_sync.enabled }}
            - name: COSMOSHUB_P2P_PERSISTENT_PEERS
              value: {{ .Values.cosmoshub_node.peers }},{{ .Values.state_sync.node_id }}
            {{- else if not .Values.cosmoshub_node.addrbook.enabled }}
            - name: COSMOSHUB_P2P_PERSISTENT_PEERS
              value: {{ .Values.cosmoshub_node.peers }}
            {{- end }}
            {{- if .Values.snapshots.enabled }}
            - name: COSMOSHUB_STATE_SYNC_SNAPSHOT_INTERVAL
              value: "2000"
            - name: COSMOSHUB_STATE_SYNC_SNAPSHOT_KEEP_RECENT
              value: "5"
            - name: COSMOSHUB_PRUNING
              value: "custom"
            - name: COSMOSHUB_PRUNING_KEEP_RECENT
              value: "100"
            - name: COSMOSHUB_PRUNING_KEEP_EVERY
              value: "2000"
            - name: COSMOSHUB_PRUNING_INTERVAL
              value: "10"
            {{- else }}
            - name: COSMOSHUB_PRUNING
              value: "{{ .Values.cosmoshub_node.pruning }}"
            - name: COSMOSHUB_PRUNING_KEEP_RECENT
              value: "{{ .Values.cosmoshub_node.pruning_keep_recent }}"
            - name: COSMOSHUB_PRUNING_KEEP_EVERY
              value: "{{ .Values.cosmoshub_node.pruning_keep_every }}"
            - name: COSMOSHUB_PRUNING_INTERVAL
              value: "{{ .Values.cosmoshub_node.pruning_interval }}"
            {{- end }}
            - name: COSMOSHUB_IAVL_DISABLE_FASTNODE
              value: "{{ .Values.cosmoshub_node.iavl_disable_fastnode }}"
            - name: COSMOSHUB_P2P_LADDR
              value: tcp://0.0.0.0:26656
            - name: COSMOSHUB_RPC_LADDR
              value: tcp://0.0.0.0:26657
            - name: COSMOSHUB_RPC_PPROF_LADDR
              value: 0.0.0.0:6060
            - name: COSMOSHUB_GRPC_ADDRESS
              value: 0.0.0.0:9090
            - name: COSMOSHUB_P2P_ADDR_BOOK_STRICT
              value: "false"
            - name: COSMOSHUB_ROSETTA_ENABLE
              value: "false"
            - name: COSMOSHUB_P2P_SEED_MODE
              value: "true"
            - name: COSMOSHUB_P2P_PEX
              value: "{{ .Values.cosmoshub_node.p2p.pex }}"
            - name: COSMOSHUB_DEBUG
              value: "{{ $.Values.debug }}"
            - name: COSMOSHUB_MINIMUM_GAS_PRICES
              value: "{{ .Values.cosmoshub_node.minimum_gas_prices }}"
            - name: SNAPSHOT_PROVIDER
              value: "{{ .Values.cosmoshub_node.snapshot_provider }}"
            {{- if .Values.state_sync.enabled }}
            - name: COSMOSHUB_STATESYNC_ENABLE
              value: "true"
            - name: COSMOSHUB_STATESYNC_RPC_SERVERS
              value: "{{ .Values.state_sync.rpc1 }},{{ .Values.state_sync.rpc2 }}"
            {{- end }}
            - name: COSMOSHUB_API_ENABLE
              value: "{{ .Values.cosmoshub_node.api.enable }}"
          ports:
            - containerPort: 26656
              name: p2p
            - containerPort: 26659
              name: kms
            - containerPort: 26660
              name: metrics
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            {{- if .Values.validator.enabled }}
            - name: cosmoshub-validator-config-toml
            {{- else }}
            - name: cosmoshub-fullnode-config-toml
            {{- end }}
              mountPath: {{ .Values.home }}/config/config.toml
              subPath: config.toml
            {{- if .Values.validator.enabled }}
            - name: cosmoshub-validator-app-toml
            {{- else }}
            - name: cosmoshub-fullnode-app-toml
            {{- end }}
              mountPath: {{ .Values.home }}/config/app.toml
              subPath: app.toml
          {{- if .Values.validator.enabled }}
            - name: node-key
              mountPath: {{ .Values.home }}/config/node_key.json
              subPath: node_key.json
            - name: priv-validator-key
              mountPath: {{ .Values.home }}/config/priv_validator_key.json
              subPath: priv_validator_key.json
          {{- end }}
          {{- if .Values.local_storage.enabled }}
            - name: local-persistent-storage
              mountPath: "{{ .Values.home }}"
          {{- else }}
            - name: home
              mountPath: "{{ .Values.home }}"
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: cosmoshub-node-config
        {{- if .Values.validator.enabled }}
        - name: cosmoshub-validator-config-toml
          configMap:
            name: cosmoshub-validator-config-toml
        - name: cosmoshub-validator-app-toml
          configMap:
            name: cosmoshub-validator-app-toml
        {{- else }}
        - name: cosmoshub-fullnode-config-toml
          configMap:
            name: cosmoshub-fullnode-config-toml
        - name: cosmoshub-fullnode-app-toml
          configMap:
            name: cosmoshub-fullnode-app-toml
        {{- end }}
      {{- if .Values.microk8s.enabled }}
        - name: home
          hostPath:
            # Ensure the file directory is created.
            path: "{{ .Values.microk8s.hostpath }}"
            type: DirectoryOrCreate
      {{- end }}
      {{- if .Values.validator.enabled }}
        - name: priv-validator-key
          secret:
            secretName: priv-validator-key
        - name: node-key
          secret:
            secretName: node-key
      {{- end }}