{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "osmosis-node.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - rpc.osmosis.{{ .Values.ingress.domain }}
    secretName: rpc.osmosis-{{ .Values.ingress.domain }}-tls
  - hosts:
    - api.osmosis.{{ .Values.ingress.domain }}
    secretName: api.osmosis-{{ .Values.ingress.domain }}-tls
  {{- end }}
  rules:
    - host: rpc.osmosis.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: osmosis-fullnode
                port:
                  number: 26657
    - host: api.osmosis.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: osmosis-fullnode
                port:
                  number: 1317
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "osmosis-node.fullname" . }}-grpc-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - grpc.osmosis.{{ .Values.ingress.domain }}
    secretName: grpc.osmosis-{{ .Values.ingress.domain }}-tls
  {{ end }}
spec:
  ingressClassName: nginx
  rules:
    - host: grpc.osmosis.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: osmosis-fullnode
                port:
                  number: 9090
{{- end }}