{{- if .Values.fullnode.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: comdex-fullnode
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 1317
      name: api
    - port: 9090
      name: grpc
    - port: 26656
      name: p2p
    - port: 26657
      name: rpc
  selector:
    comdex.network/fullnode: "{{ .Values.comdex_node.moniker }}"
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: comdex-validator
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 26656
      name: p2p
    - port: 26660
      name: metrics
    {{- if .Values.validator.tmkms }}
    - port: 26659
      name: kms
    {{- end }}
  selector:
    app: "comdex-validator"
