apiVersion: v1
kind: Service
metadata:
  name: coingecko-api
  labels:
    app: coingecko-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.coingeckoApi.servicePort }}
      targetPort: {{ .Values.coingeckoApi.servicePort }}
      protocol: TCP
      name: coingecko-api
  selector:
    app: coingecko-api
