replicaCount: 1


redis:
  image: redis:latest
  password: yourpassword
  aofEnabled: no
  allowEmptyPassword: no
  port: 6379

backendService:
  image: ghcr.io/yourproject:version
  redisPassword: yourpassword
  driveDisk: local
  aofEnabled: no
  redisConnection: local
  redisHost: redis
  redisPort: 6379
  appKey: gfhsdjgfjdsghjfhjsd
  ingressHost: host
  servicePort: 3333
  replicaCount: 1
  strategy:
    maxSurge: 1
    maxUnavailable: 0

faucet:
  image: ghcr.io/stakelab-zone/stakelab-backend:faucet
  passphrase: ""
  NearPrivateKey: ""
  servicePort: 3333
  replicaCount: 0
  strategy:
    maxSurge: 1
    maxUnavailable: 0

imagePullSecrets:
  - name: ghcr-secret
nameOverride: ""
fullnameOverride: ""

# Docker image pull policy
pullPolicy: Always

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}


service:
  type: ClusterIP

ingress:
  enabled: false
  domain: "domain.tld"
  tls: false
  annotations:
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
