# Default values for assetmantle-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "ghcr.io/akash-network/cosmos-omnibus"
  tag: "v0.3.41-assetmantle-v0.3.0"
  pullPolicy: IfNotPresent

# Common Values

keyring_backend: "test"
home: "/root/.mantleNode"
debug: "false"

# Set Values to run a single assetmantle node connected to an existing network
# Defaults to mainnet
assetmantle_node:
  api_enable: "true"
  moniker: StakeLab
  chainid: mantle-1
  # disable PEX when nodes have issues with syncing / catching up / peer dial errors/flood
  minimum_gas_prices: 0.0umntl
  net: https://snapshots.polkachu.com/genesis/assetmantle/genesis.json
  peers: df406a21ac70fbcd7ae06448fe0e7b428385ec6f@65.21.195.98:26656,89757803f40da51678451735445ad40d5b15e059@164.152.160.22:26656,96b7e522a5dfd6d41d9e75895a2db7bb2c5e83d6@95.214.52.138:26656,113a2a4c89c4e557f5e5f85eea729907e7720d12@138.201.222.230:26686,e4b985f2a609baec86af2e2af45cf1ae5bae2d50@5.34.179.199:26656,4039dc9fdc59412a9dfedac49eaee8e07c2415e6@23.88.62.189:27003,e1718c020d26d76a63a5496086f8a5ff68fb8de7@165.227.13.116:26656,9dfee52057487fdb2bd8421768a16f7412797b37@167.235.211.122:26656,38f4504f74a9fd70f158270751c31a4d146f987c@142.132.152.46:12656,f61e5c1d7897dd445508a873248e57ae553ac258@95.216.102.235:53759,8a9494ae1337efe0df805281a7ba20ddf6be1ad3@5.199.163.76:26656,3445d0e74d4c52d46b91be893b8b3027dd895413@165.227.166.249:26656,68692140af51d0c41163340f6f1222eec914c18f@142.132.248.138:26746,52afed38019330fa441af04a3c52bf6425227b3f@88.99.71.158:46656,cbb1bb6b073e65bb5a9a349e8ac2bb86348b5da1@142.132.210.135:26656,7f150cae7e3a0c63bee9e9fdadb0165096947deb@15.235.114.194:10256,8f0920cc298354c536845a5bfb19e5c3e1b42913@198.37.107.164:26656,94e3151dddac887e84b42c309e24c33ceae8026e@144.76.16.29:26656,c75a48b7dfbad051443eb79db51ab7ccc770e152@65.109.106.172:28656,a9a18c182cdc0b787565962301d96d19c9202b1a@51.81.155.189:10256,f073d57107004268a7c0f1e24433401f892eff94@144.76.63.67:26229,169a3e12d45903d961ace560a384d3bcb55092e2@3.138.118.210:26656,684ca0ac72dd5e42a9a3f1e7985acfb1828e6429@2.138.201.93:46656,5898bc79cbcbf288019363edd7f8237cb433d18c@65.21.225.207:10156,4a3a422dae276960070630ff809aba341841e65e@85.10.198.171:26656,4e1c2471efb89239fb04a4b75f9f87177fd91d00@134.65.194.95:26656,b212d5740b2e11e54f56b072dc13b6134650cfb5@169.155.45.218:26656,d2a16801e996bc71ddb2e30027a006b12b4cbcb6@62.171.182.242:23656,f2dd2c427ad98e4e4b4666fc477331377aa8c372@135.125.163.63:26646,bc573679e48cd5aeb8ac0b222a886cfaf3f70368@88.99.192.187:46656,767635fe9d2f35b9bfbcf40ad5d2e355bf9b15d3@13.234.225.229:26656,e1b058e5cfa2b836ddaa496b10911da62dcf182e@138.201.8.248:26656,e726816f42831689eab9378d5d577f1d06d25716@169.155.171.1:26656,7a29d52e27a3a663b32bf7fabcea5966e8640760@88.198.66.25:46656,da9b5a590e6bb1b2fc8dd04376964d61fb803959@94.16.109.45:26656
  seeds: 
  addrbook:
    enabled: false
    url: https://snapshots.polkachu.com/addrbook/assetmantle/addrbook.json

  # Pruning configuration
  pruning: "custom"
  pruning_keep_recent: "100"
  pruning_keep_every: "0"
  pruning_interval: "10"

  iavl_disable_fastnode: true

  proxy_app: "tcp://127.0.0.1:26658"
  block_sync: true
  db_backend: "goleveldb"
  db_dir: "data"
  log_level: "info"
  log_format: "plain"
  genesis_file: "config/genesis.json"
  priv_validator_state_file: "data/priv_validator_state.json"
  priv_validator_key_file: "config/priv_validator_key.json"
  node_key_file: "config/node_key.json"
  abci: "socket"
  filter_peers: false
  rpc:
    laddr: "tcp://0.0.0.0:26657"
    cors_allowed_origins: "[*, ]"
    cors_allowed_methods: "['HEAD', 'GET', 'POST']"
    cors_allowed_headers: "['Origin', 'Accept', 'Content-Type', 'X-Requested-With', 'X-Server-Time']"
    grpc_laddr: ""
    grpc_max_open_connections: 900
    unsafe: false
    max_open_connections: 900
    max_subscription_clients: 100
    max_subscriptions_per_client: 5
    experimental_subscription_buffer_size: 200
    experimental_websocket_write_buffer_size: 200
    experimental_close_on_slow_client: false
    timeout_broadcast_tx_commit: "10s"
    max_body_bytes: 1000000
    max_header_bytes: 1048576
    tls_cert_file: ""
    tls_key_file: ""
    pprof_laddr: "localhost:6060"
  p2p:
    laddr: "tcp://0.0.0.0:26656"
    external_address: ""
    upnp: false
    addr_book_file: "config/addrbook.json"
    addr_book_strict: true
    max_num_inbound_peers: 40
    max_num_outbound_peers: 10
    unconditional_peer_ids: ""
    persistent_peers_max_dial_period: "0s"
    flush_throttle_timeout: "100ms"
    max_packet_msg_payload_size: 1024
    send_rate: 5120000
    recv_rate: 5120000
    pex: true
    seed_mode: false
    private_peer_ids: ""
    allow_duplicate_ip: false
    handshake_timeout: "20s"
    dial_timeout: "3s"
  mempool:
    version: "v1"
    recheck: true
    broadcast: true
    wal_dir: ""
    size: 5000
    max_txs_bytes: 1073741824
    cache_size: 20000
    keep-invalid-txs-in-cache: true
    max_tx_bytes: 1048576
    max_batch_bytes: 0
    ttl-duration: "0s"
    ttl-num-blocks: 20
    max_txs: 5000
  statesync:
    enable: false
    rpc_servers: ""
    trust_height: 0
    trust_hash: ""
    trust_period: "168h0m0s"
    discovery_time: "15s"
    temp_dir: ""
    chunk_request_timeout: "10s"
    chunk_fetchers: "4"
  fastsync:
    version: "v0"
  consensus:
    wal_file: "data/cs.wal/wal"
    timeout_propose: "3s"
    timeout_propose_delta: "500ms"
    timeout_prevote: "1s"
    timeout_prevote_delta: "500ms"
    timeout_precommit: "1s"
    timeout_precommit_delta: "500ms"
    timeout_commit: "999ms"
    double_sign_check_height: 0
    skip_timeout_commit: false
    create_empty_blocks: true
    create_empty_blocks_interval: "0s"
    peer_gossip_sleep_duration: "100ms"
    peer_query_maj23_sleep_duration: "2s"
  storage:
    discard_abci_responses: false
  tx_index:
    indexer: "kv"
    psql-conn: ""
  instrumentation:
    prometheus: true
    prometheus_listen_addr: ":26660"
    max_open_connections: 900
    namespace: "cometbft"

  halt_height: 0
  halt_time: 0
  min_retain_blocks: 0
  inter_block_cache: true
  index_events: "[]"
  iavl_cache_size: 781250
  iavl-disable-fastnode: false
  iavl_lazy_loading: false
  app_db_backend: ""

  telemetry:
    enabled: true
    serviceName: ""
    enableHostname: false
    enableHostnameLabel: false
    enableServiceLabel: false
    prometheusRetentionTime: 60
    globalLabels: "[]"

  api:
    enable: true
    swagger: false
    address: "tcp://0.0.0.0:1317"
    maxOpenConnections: 1000
    rpcReadTimeout: 10
    rpcWriteTimeout: 0
    rpcMaxBodyBytes: 1000000
    enabledUnsafeCors: false

  rosetta:
    enable: false
    address: ":8080"
    blockchain: "app"
    network: "network"
    retries: 3
    offline: false
    enable_fee_suggestion: false
    gas_to_suggest: 200000
    denom_to_suggest: "uatom"

  grpc:
    enable: true
    address: "0.0.0.0:9090"
    max_recv_msg_size: "10485760"
    max_send_msg_size: "2147483647"
  grpcWeb:
    enable: true
    address: "0.0.0.0:9091"
    enableUnsafeCors: false
  stateSync:
    snapshotInterval: 0
    snapshotKeepRecent: 2

  store:
    streamers: "[]"
  streamers:
    file:
      keys: "['*', ]"
      writeDir: ""
      prefix: ""
      outputMetadata: true
      stopNodeOnError: true
      fsync: false

state_sync:
  enabled: false
  rpc1: ""
  node_id: ""
  # height_offset should equal the ASSETMANTLE_STATE_SYNC_SNAPSHOT_INTERVAL on the node which makes the state-sync snapshots
  height_offset: 2000

snapshots:
  enabled: false

microk8s:
  enabled: true
  hostpath: /data/assetmantle-validator

# Used for mounting ASSETMANTLE_HOME on a specific node
local_storage:
  enabled: false
  capacity: 100Gi
  path: /data/assetmantle-validator
  host: ""

# If the node is a validator
validator:
  enabled: true
  node_key: ""
  priv_key: ""
  tmkms: false

# If the node is a fullnode (non-validator)
fullnode:
  enabled: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  domain: "dmain.tld"

service:
  type: LoadBalancer
  loadBalancerIP: 65.109.112.162
  p2p: 26656
  rpc: 26657
  grpc: 9090
  rest: 1317
  grpc: 909
